/**
 * Page index for OpenStax *Introductory Statistics 2e* (WEB PDF), generated by
 * scripts/ingest_pdf.py from the book's table of contents. `start`/`end` are
 * printed page numbers. The URL points at the same section online.
 */
export interface BookSection {
  title: string;
  start: number;
  end: number;
  url: string;
}

export const BOOK_TITLE = "Introductory Statistics 2e (OpenStax)";
export const BOOK_URL = "https://openstax.org/books/introductory-statistics-2e";

export const bookSections: Record<string, BookSection> = {
  "1.1": { title: "Definitions of Statistics, Probability, and Key Terms", start: 5, end: 9, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-1-definitions-of-statistics-probability-and-key-terms" },
  "1.2": { title: "Data, Sampling, and Variation in Data and Sampling", start: 10, end: 25, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-2-data-sampling-and-variation-in-data-and-sampling" },
  "1.3": { title: "Frequency, Frequency Tables, and Levels of Measurement", start: 26, end: 33, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-3-frequency-frequency-tables-and-levels-of-measurement" },
  "1.4": { title: "Experimental Design and Ethics", start: 34, end: 37, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-4-experimental-design-and-ethics" },
  "1.5": { title: "Data Collection Experiment", start: 38, end: 39, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-5-data-collection-experiment" },
  "1.6": { title: "Sampling Experiment", start: 40, end: 64, url: "https://openstax.org/books/introductory-statistics-2e/pages/1-6-sampling-experiment" },
  "2.1": { title: "Stem-and-Leaf Graphs (Stemplots), Line Graphs, and Bar Graphs", start: 66, end: 74, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-1-stem-and-leaf-graphs-stemplots-line-graphs-and-bar-graphs" },
  "2.2": { title: "Histograms, Frequency Polygons, and Time Series Graphs", start: 75, end: 85, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-2-histograms-frequency-polygons-and-time-series-graphs" },
  "2.3": { title: "Measures of the Location of the Data", start: 86, end: 93, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-3-measures-of-the-location-of-the-data" },
  "2.4": { title: "Box Plots", start: 94, end: 97, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-4-box-plots" },
  "2.5": { title: "Measures of the Center of the Data", start: 98, end: 103, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-5-measures-of-the-center-of-the-data" },
  "2.6": { title: "Skewness and the Mean, Median, and Mode", start: 104, end: 106, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-6-skewness-and-the-mean-median-and-mode" },
  "2.7": { title: "Measures of the Spread of the Data", start: 107, end: 117, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-7-measures-of-the-spread-of-the-data" },
  "2.8": { title: "Descriptive Statistics", start: 118, end: 166, url: "https://openstax.org/books/introductory-statistics-2e/pages/2-8-descriptive-statistics" },
  "3.1": { title: "Terminology", start: 168, end: 171, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-1-terminology" },
  "3.2": { title: "Independent and Mutually Exclusive Events", start: 172, end: 178, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-2-independent-and-mutually-exclusive-events" },
  "3.3": { title: "Two Basic Rules of Probability", start: 179, end: 182, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-3-two-basic-rules-of-probability" },
  "3.4": { title: "Contingency Tables", start: 183, end: 188, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-4-contingency-tables" },
  "3.5": { title: "Tree and Venn Diagrams", start: 189, end: 195, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-5-tree-and-venn-diagrams" },
  "3.6": { title: "Probability Topics", start: 196, end: 226, url: "https://openstax.org/books/introductory-statistics-2e/pages/3-6-probability-topics" },
  "4.1": { title: "Probability Distribution Function (PDF) for a Discrete Random Variable", start: 228, end: 229, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-1-probability-distribution-function-pdf-for-a-discrete-random-variable" },
  "4.2": { title: "Mean or Expected Value and Standard Deviation", start: 230, end: 236, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-2-mean-or-expected-value-and-standard-deviation" },
  "4.3": { title: "Binomial Distribution", start: 237, end: 241, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-3-binomial-distribution" },
  "4.4": { title: "Geometric Distribution", start: 242, end: 246, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-4-geometric-distribution" },
  "4.5": { title: "Hypergeometric Distribution", start: 247, end: 249, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-5-hypergeometric-distribution" },
  "4.6": { title: "Poisson Distribution", start: 250, end: 254, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-6-poisson-distribution" },
  "4.7": { title: "Discrete Distribution (Playing Card Experiment)", start: 255, end: 257, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-7-discrete-distribution-playing-card-experiment" },
  "4.8": { title: "Discrete Distribution (Dice Experiment Using Three Regular Dice)", start: 258, end: 290, url: "https://openstax.org/books/introductory-statistics-2e/pages/4-8-discrete-distribution-dice-experiment-using-three-regular-dice" },
  "5.1": { title: "Continuous Probability Functions", start: 292, end: 294, url: "https://openstax.org/books/introductory-statistics-2e/pages/5-1-continuous-probability-functions" },
  "5.2": { title: "The Uniform Distribution", start: 295, end: 301, url: "https://openstax.org/books/introductory-statistics-2e/pages/5-2-the-uniform-distribution" },
  "5.3": { title: "The Exponential Distribution", start: 302, end: 312, url: "https://openstax.org/books/introductory-statistics-2e/pages/5-3-the-exponential-distribution" },
  "5.4": { title: "Continuous Distribution", start: 313, end: 334, url: "https://openstax.org/books/introductory-statistics-2e/pages/5-4-continuous-distribution" },
  "6.1": { title: "The Standard Normal Distribution", start: 336, end: 339, url: "https://openstax.org/books/introductory-statistics-2e/pages/6-1-the-standard-normal-distribution" },
  "6.2": { title: "Using the Normal Distribution", start: 340, end: 346, url: "https://openstax.org/books/introductory-statistics-2e/pages/6-2-using-the-normal-distribution" },
  "6.3": { title: "Normal Distribution (Lap Times)", start: 347, end: 347, url: "https://openstax.org/books/introductory-statistics-2e/pages/6-3-normal-distribution-lap-times" },
  "6.4": { title: "Normal Distribution (Pinkie Length)", start: 348, end: 364, url: "https://openstax.org/books/introductory-statistics-2e/pages/6-4-normal-distribution-pinkie-length" },
  "7.1": { title: "The Central Limit Theorem for Sample Means (Averages)", start: 366, end: 369, url: "https://openstax.org/books/introductory-statistics-2e/pages/7-1-the-central-limit-theorem-for-sample-means-averages" },
  "7.2": { title: "The Central Limit Theorem for Sums", start: 370, end: 372, url: "https://openstax.org/books/introductory-statistics-2e/pages/7-2-the-central-limit-theorem-for-sums" },
  "7.3": { title: "Using the Central Limit Theorem", start: 373, end: 380, url: "https://openstax.org/books/introductory-statistics-2e/pages/7-3-using-the-central-limit-theorem" },
  "7.4": { title: "Central Limit Theorem (Pocket Change)", start: 381, end: 383, url: "https://openstax.org/books/introductory-statistics-2e/pages/7-4-central-limit-theorem-pocket-change" },
  "7.5": { title: "Central Limit Theorem (Cookie Recipes)", start: 384, end: 404, url: "https://openstax.org/books/introductory-statistics-2e/pages/7-5-central-limit-theorem-cookie-recipes" },
  "8.1": { title: "A Single Population Mean using the Normal Distribution", start: 407, end: 415, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-1-a-single-population-mean-using-the-normal-distribution" },
  "8.2": { title: "A Single Population Mean using the Student t Distribution", start: 416, end: 419, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-2-a-single-population-mean-using-the-student-t-distribution" },
  "8.3": { title: "A Population Proportion", start: 420, end: 426, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-3-a-population-proportion" },
  "8.4": { title: "Confidence Interval (Home Costs)", start: 427, end: 428, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-4-confidence-interval-home-costs" },
  "8.5": { title: "Confidence Interval (Place of Birth)", start: 429, end: 429, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-5-confidence-interval-place-of-birth" },
  "8.6": { title: "Confidence Interval (Women's Heights)", start: 430, end: 460, url: "https://openstax.org/books/introductory-statistics-2e/pages/8-6-confidence-interval-women-s-heights" },
  "9.1": { title: "Null and Alternative Hypotheses", start: 462, end: 463, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-1-null-and-alternative-hypotheses" },
  "9.2": { title: "Outcomes and the Type I and Type II Errors", start: 464, end: 465, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-2-outcomes-and-the-type-i-and-type-ii-errors" },
  "9.3": { title: "Probability Distribution Needed for Hypothesis Testing", start: 466, end: 466, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-3-probability-distribution-needed-for-hypothesis-testing" },
  "9.4": { title: "Rare Events, the Sample, Decision and Conclusion", start: 467, end: 468, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-4-rare-events-the-sample-decision-and-conclusion" },
  "9.5": { title: "Additional Information and Full Hypothesis Test Examples", start: 469, end: 482, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-5-additional-information-and-full-hypothesis-test-examples" },
  "9.6": { title: "Hypothesis Testing of a Single Mean and Single Proportion", start: 483, end: 510, url: "https://openstax.org/books/introductory-statistics-2e/pages/9-6-hypothesis-testing-of-a-single-mean-and-single-proportion" },
  "10.1": { title: "Two Population Means with Unknown Standard Deviations", start: 512, end: 519, url: "https://openstax.org/books/introductory-statistics-2e/pages/10-1-two-population-means-with-unknown-standard-deviations" },
  "10.2": { title: "Two Population Means with Known Standard Deviations", start: 520, end: 522, url: "https://openstax.org/books/introductory-statistics-2e/pages/10-2-two-population-means-with-known-standard-deviations" },
  "10.3": { title: "Comparing Two Independent Population Proportions", start: 523, end: 526, url: "https://openstax.org/books/introductory-statistics-2e/pages/10-3-comparing-two-independent-population-proportions" },
  "10.4": { title: "Matched or Paired Samples", start: 527, end: 531, url: "https://openstax.org/books/introductory-statistics-2e/pages/10-4-matched-or-paired-samples" },
  "10.5": { title: "Hypothesis Testing for Two Means and Two Proportions", start: 532, end: 562, url: "https://openstax.org/books/introductory-statistics-2e/pages/10-5-hypothesis-testing-for-two-means-and-two-proportions" },
  "11.1": { title: "Facts About the Chi-Square Distribution", start: 564, end: 564, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-1-facts-about-the-chi-square-distribution" },
  "11.2": { title: "Goodness-of-Fit Test", start: 565, end: 573, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-2-goodness-of-fit-test" },
  "11.3": { title: "Test of Independence", start: 574, end: 577, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-3-test-of-independence" },
  "11.4": { title: "Test for Homogeneity", start: 578, end: 581, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-4-test-for-homogeneity" },
  "11.5": { title: "Comparison of the Chi-Square Tests", start: 582, end: 582, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-5-comparison-of-the-chi-square-tests" },
  "11.6": { title: "Test of a Single Variance", start: 582, end: 583, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-6-test-of-a-single-variance" },
  "11.7": { title: "Lab 1: Chi-Square Goodness-of-Fit", start: 584, end: 586, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-7-lab-1-chi-square-goodness-of-fit" },
  "11.8": { title: "Lab 2: Chi-Square Test of Independence", start: 587, end: 616, url: "https://openstax.org/books/introductory-statistics-2e/pages/11-8-lab-2-chi-square-test-of-independence" },
  "12.1": { title: "Linear Equations", start: 617, end: 619, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-1-linear-equations" },
  "12.2": { title: "Scatter Plots", start: 620, end: 622, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-2-scatter-plots" },
  "12.3": { title: "The Regression Equation", start: 623, end: 630, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-3-the-regression-equation" },
  "12.4": { title: "Testing the Significance of the Correlation Coefficient", start: 631, end: 634, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-4-testing-the-significance-of-the-correlation-coefficient" },
  "12.5": { title: "Prediction", start: 635, end: 635, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-5-prediction" },
  "12.6": { title: "Outliers", start: 636, end: 643, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-6-outliers" },
  "12.7": { title: "Regression (Distance from School)", start: 644, end: 645, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-7-regression-distance-from-school" },
  "12.8": { title: "Regression (Textbook Cost)", start: 646, end: 646, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-8-regression-textbook-cost" },
  "12.9": { title: "Regression (Fuel Efficiency)", start: 647, end: 678, url: "https://openstax.org/books/introductory-statistics-2e/pages/12-9-regression-fuel-efficiency" },
  "13.1": { title: "One-Way ANOVA", start: 679, end: 679, url: "https://openstax.org/books/introductory-statistics-2e/pages/13-1-one-way-anova" },
  "13.2": { title: "The F Distribution and the F-Ratio", start: 680, end: 683, url: "https://openstax.org/books/introductory-statistics-2e/pages/13-2-the-f-distribution-and-the-f-ratio" },
  "13.3": { title: "Facts About the F Distribution", start: 684, end: 689, url: "https://openstax.org/books/introductory-statistics-2e/pages/13-3-facts-about-the-f-distribution" },
  "13.4": { title: "Test of Two Variances", start: 690, end: 692, url: "https://openstax.org/books/introductory-statistics-2e/pages/13-4-test-of-two-variances" },
  "13.5": { title: "Lab: One-Way ANOVA", start: 693, end: 693, url: "https://openstax.org/books/introductory-statistics-2e/pages/13-5-lab-one-way-anova" },
};

export const chapterStart: Record<number, number> = {
  1: 5,
  2: 65,
  3: 167,
  4: 227,
  5: 291,
  6: 335,
  7: 365,
  8: 405,
  9: 461,
  10: 511,
  11: 563,
  12: 617,
  13: 679,
};

/** Page range covered by a whole chapter (its numbered sections). */
export const chapterPages = (n: number): { start: number; end: number } | undefined => {
  const secs = Object.entries(bookSections).filter(([k]) => k.startsWith(`${n}.`)).map(([, v]) => v);
  if (!secs.length) return undefined;
  return { start: Math.min(...secs.map((s) => s.start)), end: Math.max(...secs.map((s) => s.end)) };
};
