import { mc, tf, num, text, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u1";

const l1 = lesson("u1.1", "1.1", "Statistics, probability, and key terms",
  "Statistics is the science of collecting, organizing, analyzing, and interpreting data. You will meet the vocabulary that underpins everything else: population vs. sample, parameter vs. statistic, and variable vs. data.",
  ["Population: the whole group of interest. Sample: the part we actually measure.",
   "Parameter: a number describing a population. Statistic: a number describing a sample.",
   "Variable: a characteristic that varies (X). Data: the actual observed values.",
   "Descriptive statistics summarize data; inferential statistics use samples to draw conclusions about populations.",
   "Probability quantifies chance and is the mathematical tool behind inference."],
  [
    mc(p, "A researcher wants to know the average number of hours all students at a 20,000-student university sleep per night. She surveys 300 students. What is the population?",
      ["All 20,000 students at the university", "The 300 surveyed students", "The average hours of sleep", "Students who sleep fewer than 8 hours"],
      "The population is the entire group the researcher wants to draw conclusions about: every student at the university. The 300 students are the sample."),
    mc(p, "In the same study, the average of 7.1 hours computed from the 300 surveyed students is a…",
      ["statistic", "parameter", "variable", "population"],
      "A number computed from a sample is a statistic. The (unknown) true average for all 20,000 students would be the parameter."),
    match(p, "Match each term to its definition.", [
      ["Population", "The entire group being studied"],
      ["Sample", "A subset actually measured"],
      ["Parameter", "A number summarizing a population"],
      ["Statistic", "A number summarizing a sample"],
    ], "Remember P goes with P (population → parameter) and S goes with S (sample → statistic)."),
    mc(p, "Which of the following is an example of inferential statistics?",
      ["Using a sample of 500 voters to estimate the proportion of all voters who favor a candidate",
       "Reporting the median household income of the households in a survey",
       "Drawing a bar graph of survey responses",
       "Calculating the average age of the employees at a company from the full payroll"],
      "Inferential statistics uses sample information to reach conclusions about a larger population. The other options merely describe the data at hand."),
    classify(p, "Sort each item as a variable or data.", ["Variable", "Data"], [
      ["X = the number of siblings a student has", "Variable"],
      ["2, 0, 1, 3, 1", "Data"],
      ["Y = a person's eye color", "Variable"],
      ["blue, brown, brown, green", "Data"],
    ], "A variable is the characteristic being measured (usually written with a capital letter). Data are the actual values observed for that variable."),
    tf(p, "A parameter is usually known exactly, while a statistic must be estimated.", false,
      "It is the other way around. Parameters describe entire populations and are usually unknown; we compute statistics from samples to estimate them."),
    text(p, "The proportion of all registered voters in a state who support a bill is an example of a ___ (parameter or statistic).", ["parameter"],
      "It describes the whole population of registered voters, so it is a parameter (typically written p)."),
    mc(p, "A weather app says there is a 70% chance of rain tomorrow. This number is best described as a…",
      ["probability", "parameter", "statistic", "sample"],
      "A probability is a number between 0 and 1 (or 0% and 100%) that measures how likely an event is."),
    mc(p, "Which symbol conventionally represents a sample mean?",
      ["x̄", "μ", "σ", "p"],
      "x̄ (x-bar) is the sample mean; μ is the population mean; σ is the population standard deviation; p is a population proportion."),
    G.sampleVsPopulation,
    mc(p, "Which term describes a variable such as height, age, or number of siblings, whose values are numbers you can meaningfully average?",
      ["Numerical (quantitative) variable", "Categorical variable", "Parameter", "Population"],
      "Numerical variables take number values that represent counts or measurements. Categorical (qualitative) variables take labels such as hair color."),
    mc(p, "In a survey of 250 shoppers, 40 said they had used a coupon. The value 40/250 = 0.16 is called a…",
      ["proportion (a sample statistic)", "parameter", "variable", "population"],
      "A proportion is the number of successes divided by the total in the sample. Computed from a sample, it is a statistic; the corresponding population value is a parameter."),
  ]);

const l2 = lesson("u1.2", "1.2", "Data, sampling, and variation",
  "Data come in qualitative (categorical) and quantitative (numerical) flavors, and quantitative data may be discrete or continuous. Good conclusions require good samples, so learn the random sampling methods and the ways sampling can go wrong.",
  ["Qualitative (categorical): labels such as color or zip code. Quantitative: counts or measurements.",
   "Quantitative discrete: counted values (number of pets). Quantitative continuous: measured values (weight, time).",
   "Random sampling methods: simple random, stratified, systematic, cluster. Convenience sampling is not random.",
   "Sampling with vs. without replacement. Sampling error: natural sample-to-sample variation. Nonsampling error: human problems such as poor design or data entry mistakes.",
   "Beware bias: nonresponse, self-selection, undercoverage, misleading questions."],
  [
    classify(p, "Classify each variable by data type.", ["Qualitative", "Quantitative discrete", "Quantitative continuous"], [
      ["Favorite pizza topping", "Qualitative"],
      ["Number of cars a family owns", "Quantitative discrete"],
      ["Time to run 5 km", "Quantitative continuous"],
      ["Zip code", "Qualitative"],
      ["Weight of a backpack", "Quantitative continuous"],
      ["Number of text messages sent today", "Quantitative discrete"],
    ], "Categorical labels are qualitative even when they are numbers you would never average (zip codes). Counts are discrete; measurements on a continuous scale are continuous."),
    mc(p, "Which of these is quantitative continuous data?",
      ["The amount of rainfall in inches during April", "The number of rainy days in April", "The month with the most rain", "The type of cloud observed"],
      "Rainfall amount is measured and can take any value in a range, so it is continuous. Number of rainy days is a count (discrete)."),
    G.samplingMethod,
    G.samplingMethod,
    mc(p, "A school district wants to survey teachers' opinions. It randomly picks 4 of its 30 schools and surveys every teacher in those 4 schools. This is…",
      ["cluster sampling", "stratified sampling", "systematic sampling", "simple random sampling"],
      "Cluster sampling randomly selects whole groups (clusters) and includes everyone in the chosen groups. Stratified sampling would take some teachers from every school."),
    mc(p, "What is the main advantage of stratified sampling over simple random sampling?",
      ["It guarantees that every subgroup (stratum) is represented in the sample",
       "It requires a smaller population",
       "It eliminates all sampling error",
       "It allows the researcher to choose the most cooperative participants"],
      "By sampling within each stratum, stratified sampling ensures that subgroups appear in the sample in appropriate proportions. No method eliminates sampling error."),
    mc(p, "A TV station asks viewers to text their opinion on a new tax. 8,000 people respond and 71% oppose it. Why is this result unreliable?",
      ["The sample is self-selected, so it is likely biased toward people with strong opinions",
       "The sample is too small",
       "Texting is a form of cluster sampling",
       "Percentages cannot be computed from text messages"],
      "Voluntary response (self-selected) samples over-represent people who feel strongly. A large sample size does not fix a biased sampling method."),
    tf(p, "Two different simple random samples of the same size from the same population will usually give slightly different sample means.", true,
      "This natural variability between samples is called sampling variability (sampling error). It is expected, not a mistake."),
    mc(p, "Sampling without replacement means…",
      ["once a member is selected, it cannot be selected again",
       "members are put back before the next draw",
       "the sample must be at least half the population",
       "the sample is chosen from a different population"],
      "Without replacement, each member can appear at most once. For large populations the difference from sampling with replacement is negligible."),
    mc(p, "A survey asks, \"Do you agree that the reckless city council should stop wasting money on the stadium?\" What problem does this illustrate?",
      ["A leading (biased) question", "Nonresponse bias", "Undercoverage", "Sampling error"],
      "The wording pushes respondents toward a particular answer. Good questions are neutral."),
    mc(p, "A poll surveys only people with landline telephones. Younger adults are much less likely to have landlines. Which problem is this?",
      ["Undercoverage", "Sampling error", "Nonresponse", "Replacement error"],
      "Undercoverage occurs when part of the population (here, younger adults) has little or no chance of being sampled."),
    order(p, "Put the steps of selecting a systematic sample in order.", [
      "List the population and decide the sample size n",
      "Compute k = population size ÷ n",
      "Randomly choose a starting point among the first k members",
      "Select every kth member after the starting point",
    ], "Systematic sampling needs a random start; after that, members are chosen at fixed intervals."),
    mc(p, "A sample is called representative when…",
      ["its characteristics closely match those of the population it came from", "it has at least 1,000 members", "it was collected quickly", "every member volunteered"],
      "Random sampling methods are used precisely because they tend to produce representative samples. Size alone does not make a sample representative."),
    mc(p, "A gym surveys its members about how much people in the city exercise. What problem does this illustrate?",
      ["Sampling bias: gym members are not representative of the whole city", "Sampling error", "A leading question", "Nonresponse"],
      "Sampling bias occurs when the method of selection systematically favors certain outcomes. Gym members exercise more than the typical resident, so the estimate will be too high."),
    classify(p, "Is each problem a sampling error or a nonsampling error?", ["Sampling error", "Nonsampling error"], [
      ["Two random samples of 40 patients give slightly different mean recovery times", "Sampling error"],
      ["Respondents exaggerate how often they exercise", "Nonsampling error"],
      ["A data-entry clerk types 71 instead of 17", "Nonsampling error"],
      ["A survey question is worded to favor one answer", "Nonsampling error"],
    ], "Sampling error is the natural variation from one random sample to another. Nonsampling errors are human problems: poor design, biased methods, wrong information, data entry mistakes."),
    mc(p, "Two well-run studies use different random samples of the same size from the same population. Their data are not identical. What is the most reasonable conclusion?",
      ["This is expected: different random samples naturally vary (sampling error)", "One of the studies must have made a mistake", "The population must have changed", "Random sampling does not work"],
      "Different samples give different data. That is not an error in the everyday sense; it is the sampling variability that statistics is built to handle."),
    mc(p, "A researcher randomly selects a starting house on a street and then interviews the resident of every eighth house. The sampling method is…",
      ["systematic", "simple random", "stratified", "cluster"],
      "A random start followed by every nth member is systematic sampling."),
  ]);

const l3 = lesson("u1.3", "1.3", "Frequency tables and levels of measurement",
  "Frequency tables organize data by counting how often each value appears. Relative frequency turns counts into proportions and cumulative relative frequency accumulates them. Levels of measurement (nominal, ordinal, interval, ratio) tell you what arithmetic makes sense.",
  ["Frequency: count. Relative frequency: count ÷ total. Cumulative relative frequency: running total of relative frequencies.",
   "Relative frequencies sum to 1 (allowing for rounding).",
   "Nominal: names only. Ordinal: ordered categories, differences meaningless.",
   "Interval: ordered with meaningful differences but no true zero (°C, calendar years).",
   "Ratio: meaningful differences and a true zero (height, money, time), so ratios make sense."],
  [
    G.relativeFrequency,
    G.relativeFrequency,
    num(p, "Twenty students reported how many pets they own. Five said 0, eight said 1, four said 2, and three said 3 or more. What is the relative frequency of owning exactly 1 pet?", 0.4,
      "Relative frequency = 8/20 = 0.40.", { tolerance: 0.005 }),
    num(p, "Using the same data (0: 5, 1: 8, 2: 4, 3+: 3), what is the cumulative relative frequency for owning 2 or fewer pets?", 0.85,
      "Cumulative frequency for ≤ 2 pets = 5 + 8 + 4 = 17. 17/20 = 0.85.", { tolerance: 0.005 }),
    classify(p, "Classify each variable by its level of measurement.", ["Nominal", "Ordinal", "Interval", "Ratio"], [
      ["Jersey numbers of soccer players", "Nominal"],
      ["Movie rating from 1 to 5 stars", "Ordinal"],
      ["Temperature in degrees Fahrenheit", "Interval"],
      ["Annual income in dollars", "Ratio"],
      ["Year a building was constructed", "Interval"],
      ["Number of children in a family", "Ratio"],
    ], "Nominal = names; ordinal = ordered but gaps not comparable; interval = equal gaps but arbitrary zero (0°F is not 'no temperature'); ratio = true zero so 40 is twice 20."),
    mc(p, "Which statement about interval-level data is correct?",
      ["Differences are meaningful, but ratios are not because there is no true zero",
       "It can only be ordered, not subtracted",
       "It has a true zero, so ratios are meaningful",
       "It consists of category names only"],
      "With interval data (like °C), 30° − 20° = 20° − 10° is meaningful, but 30° is not 'twice as hot' as 15° because 0° is arbitrary."),
    tf(p, "The relative frequencies in a table must always add to exactly 1.00 even after rounding.", false,
      "They should sum to 1 in principle, but rounding each entry can make the printed sum slightly off (like 0.99 or 1.01). That is acceptable."),
    mc(p, "In a frequency table, the cumulative relative frequency of the last row should be…",
      ["1 (or very close to it)", "0", "Equal to the largest frequency", "Equal to the sample size"],
      "By the last row every observation has been counted, so the running total of relative frequencies reaches 1."),
    mc(p, "Which level of measurement allows the widest range of arithmetic (ordering, subtraction, and ratios)?",
      ["Ratio", "Interval", "Ordinal", "Nominal"],
      "Ratio data have a true zero, so all of ordering, differences, and ratios are meaningful."),
    mc(p, "A frequency table of exam scores shows a frequency of 6 for the score 85. What does this mean?",
      ["Six students scored exactly 85", "The score 85 is 6% of the total", "Six students scored 85 or lower", "The average score is 85 plus 6"],
      "Frequency counts occurrences of that value. Percentages and cumulative counts are different columns."),
    classify(p, "Classify each variable by its level of measurement (as in the book's practice set).", ["Nominal", "Ordinal", "Interval", "Ratio"], [
      ["Social security numbers", "Nominal"],
      ["Letter grades A, B, C, D, F", "Ordinal"],
      ["Oven temperatures in °F: 250, 300, 350", "Interval"],
      ["Distance in miles to the nearest grocery store", "Ratio"],
      ["Calendar years such as 1066 and 1492", "Interval"],
    ], "Numbers used only as labels are nominal. Ordered categories are ordinal. Temperature and calendar years have equal intervals but no true zero, so they are interval. Distance has a true zero, so it is ratio."),
    mc(p, "Survival times in days are grouped into classes 0.5–6.5, 6.5–12.5, 12.5–18.5, … Why do the boundaries end in .5?",
      ["So that whole-number data values never fall exactly on a boundary between two classes", "Because days are measured in halves", "To make the classes unequal in width", "It is a typographical convention with no purpose"],
      "Choosing boundaries halfway between possible values puts each observation unambiguously into one class. Each class here has width 6."),
  ]);

const l4 = lesson("u1.4", "1.4", "Experimental design and ethics",
  "Observational studies watch what happens; experiments deliberately apply a treatment. Only well-designed experiments with random assignment and control of lurking variables can establish cause and effect. Ethical research protects participants and reports honestly.",
  ["Explanatory variable: the treatment or factor manipulated. Response variable: the outcome measured.",
   "Lurking variable: an unmeasured factor that could explain a result. Control it with random assignment.",
   "Control group and placebo let researchers separate the treatment effect from the placebo effect.",
   "Blinding: participants (single-blind) and also evaluators (double-blind) do not know who got which treatment.",
   "Ethics: informed consent, minimize risk, honest reporting; institutional review boards oversee studies."],
  [
    mc(p, "Researchers randomly assign 200 volunteers to take either a new supplement or an identical-looking sugar pill, then measure changes in blood pressure after 8 weeks. What is the explanatory variable?",
      ["Which pill the participant took (supplement or placebo)", "The change in blood pressure", "The 200 volunteers", "The 8-week duration"],
      "The explanatory variable is what the researchers manipulate: the treatment. Blood pressure change is the response variable."),
    mc(p, "In that study, why is the sugar pill used?",
      ["So that any improvement due only to the expectation of treatment (placebo effect) can be separated from the supplement's true effect",
       "To make the study cheaper",
       "Because sugar also lowers blood pressure",
       "So participants can choose which group they prefer"],
      "The placebo group experiences everything except the active ingredient, so differences between groups isolate the supplement's effect."),
    mc(p, "A study finds that people who drink more coffee have higher rates of lung cancer. A likely lurking variable is…",
      ["Smoking, which is associated with both coffee drinking and lung cancer", "The brand of coffee", "The size of the coffee cup", "The time of day coffee is consumed"],
      "A lurking variable is related to both the explanatory and response variables. Smokers tend to drink more coffee, and smoking causes lung cancer, so coffee looks guilty by association."),
    classify(p, "Is each scenario an observational study or an experiment?", ["Observational study", "Experiment"], [
      ["Compare heart health of people who already run marathons with people who do not", "Observational study"],
      ["Randomly assign plots of land to receive fertilizer A or B and compare yields", "Experiment"],
      ["Survey households about their internet speed and satisfaction", "Observational study"],
      ["Give half of a class a new study app and compare test scores with the other half", "Experiment"],
    ], "In an experiment the researcher assigns the treatment. In an observational study the researcher only records what already happens."),
    mc(p, "What does double-blind mean?",
      ["Neither the participants nor the people evaluating the results know who received which treatment",
       "Two placebos are used",
       "Participants are tested twice",
       "The study is repeated by a second research team"],
      "Double-blinding prevents both participant expectations and evaluator bias from influencing the measured results."),
    tf(p, "Random assignment of subjects to treatments helps balance lurking variables across the treatment groups.", true,
      "Because assignment is random, any lurking variables should be spread roughly evenly between groups, so differences can be attributed to the treatment."),
    mc(p, "Which of the following is an ethical requirement for research on human subjects?",
      ["Obtaining informed consent from participants", "Guaranteeing the study finds a significant result", "Paying participants at least minimum wage", "Using at least 1,000 participants"],
      "Participants must understand the study and agree to take part. Institutional review boards check for this and for minimizing risk."),
    mc(p, "A pharmaceutical company publishes only the trials in which its drug looked effective and quietly shelves the rest. This is a violation of…",
      ["honest and complete reporting of results", "informed consent", "random assignment", "the placebo principle"],
      "Selective reporting misleads readers about the true evidence. Ethical research reports all results, favorable or not."),
    match(p, "Match the design term to its meaning.", [
      ["Treatment", "The condition applied to a group"],
      ["Control group", "Receives no treatment or a placebo"],
      ["Response variable", "The outcome that is measured"],
      ["Lurking variable", "An unmeasured factor that could explain results"],
    ], "These four ideas are the backbone of experimental design."),
    mc(p, "Why can an observational study generally NOT prove cause and effect?",
      ["Because the researcher does not control who gets the treatment, so lurking variables may explain the association",
       "Because observational studies never use random samples",
       "Because they do not use numbers",
       "Because they are always too small"],
      "Without controlled assignment, an association may be due to other differences between the groups rather than the factor being studied."),
    mc(p, "Forty tomato plants are randomly assigned to receive one of two fertilizers, and each plant's yield is measured. What is the experimental unit?",
      ["A single tomato plant", "The fertilizer", "The yield", "The 40 plants together"],
      "The experimental unit is the single individual (person, animal, plant, object) to which a treatment is applied and on which the response is measured."),
    mc(p, "In an experiment, not telling participants which treatment they are receiving is called…",
      ["blinding", "random assignment", "informed consent", "clustering"],
      "Blinding prevents participants' expectations from influencing the response. When the researchers who work with the subjects are also kept unaware, the experiment is double-blind."),
    mc(p, "Patients who used a memory-training app were also enrolled in an exercise program, while the comparison group was not. Improvement was higher in the app group. What is the problem?",
      ["The exercise program is a lurking variable, so the improvement cannot be attributed to the app", "The sample was too small", "The app group should not have been measured", "There is no problem; the app works"],
      "When treatment groups differ in more than the treatment, any difference in outcome is confounded. Properly designed experiments differ only in the imposed treatment."),
  ]);

export const unit1 = unit(1, "Sampling and Data", "Populations, samples, data types, and how to collect data you can trust.", "🔍", "#58cc02", [l1, l2, l3, l4]);
