import { mc, tf, num, text, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u2";

const l1 = lesson("u2.1", "2.1", "Stem-and-leaf plots, line graphs, and bar graphs",
  "Before computing anything, look at the data. Stem-and-leaf plots keep every value visible, line graphs track frequency across values, and bar graphs compare categories.",
  ["Stem-and-leaf: stems are leading digits, leaves are final digits; leaves stay in order.",
   "Stemplots show shape and outliers while keeping the raw data.",
   "Bar graphs compare categories; bars do not touch and order can be chosen for clarity.",
   "Line graphs plot frequency (y) against values (x)."],
  [
    G.modeOfData, G.medianOfData,
    mc(p, "In a stem-and-leaf plot of test scores, the row '7 | 2 5 5 8' represents which values?",
      ["72, 75, 75, 78", "7, 2, 5, 5, 8", "72, 75, 78", "725, 758"],
      "The stem 7 is the tens digit; each leaf is a ones digit. Repeated leaves are repeated values."),
    num(p, "A stem-and-leaf plot has rows 3 | 1 4, 4 | 0 0 7, 5 | 2. How many data values are there?", 6,
      "Count the leaves: 2 + 3 + 1 = 6 values (31, 34, 40, 40, 47, 52).", { tolerance: 0 }),
    num(p, "Using the plot 3 | 1 4, 4 | 0 0 7, 5 | 2, what is the largest value?", 52,
      "The last row has stem 5 and leaf 2, giving 52.", { tolerance: 0 }),
    mc(p, "Which graph is most appropriate for comparing the number of students in each of five majors?",
      ["Bar graph", "Stem-and-leaf plot", "Line graph of frequency vs. value", "Scatter plot"],
      "Majors are categories, so a bar graph is the natural choice. Stemplots and frequency line graphs are for quantitative data."),
    tf(p, "A stem-and-leaf plot loses the original data values, showing only the counts.", false,
      "That is a strength of stemplots: every original value can be read back from the stems and leaves."),
    mc(p, "Data: 12, 15, 15, 21, 23, 30. Which stem has the most leaves?",
      ["1", "2", "3", "They all tie"],
      "Stem 1 has leaves 2, 5, 5 (three values); stem 2 has 1, 3; stem 3 has 0."),
    mc(p, "A line graph shows the number of students (y-axis) who reported each number of siblings (x-axis). The tallest point is at x = 1. What does this mean?",
      ["More students reported 1 sibling than any other number", "The average number of siblings is 1", "Only one student was surveyed", "Every student has at least 1 sibling"],
      "In a frequency line graph, the height is the count for that value, so the peak is the most common value (the mode)."),
    mc(p, "What should the bars of a bar graph for qualitative data have in common?",
      ["The same width, with gaps between them", "Touching sides, like a histogram", "Heights that always add to 100", "Random ordering"],
      "Equal widths with gaps signal that the categories are separate; heights represent frequency or relative frequency."),
    match(p, "Match the graph type to its best use.", [
      ["Stem-and-leaf plot", "Small quantitative data set, keep every value"],
      ["Bar graph", "Compare categories"],
      ["Line graph", "Frequency of each quantitative value"],
      ["Histogram", "Large quantitative data set grouped into intervals"],
    ], "Choosing the right graph starts with asking whether data are categorical or quantitative and how large the set is."),
  ]);

const l2 = lesson("u2.2", "2.2", "Histograms, frequency polygons, and time series",
  "A histogram groups continuous data into intervals of equal width and uses touching bars whose heights show frequency or relative frequency. Its shape reveals symmetry, skewness, and outliers.",
  ["Histogram bars touch; the x-axis shows interval boundaries, the y-axis frequency or relative frequency.",
   "Convention: start the first boundary slightly below the smallest value (e.g., 0.5 below) to avoid values on a boundary.",
   "Width = (largest − smallest) ÷ number of bars, then adjust for convenience.",
   "Frequency polygons connect interval midpoints; time series graphs plot values against time."],
  [
    num(p, "Data range from 12 to 84 and you want 8 bars of equal width. What is the width of each bar (before rounding for convenience)?", 9,
      "Width = (84 − 12)/8 = 72/8 = 9.", { tolerance: 0.01 }),
    mc(p, "Why do statisticians often start a histogram's first boundary at a value like 11.5 instead of 12 when the smallest data value is 12?",
      ["So that no data value sits exactly on a boundary between two bars", "To make the histogram look taller", "Because histograms cannot start at whole numbers", "To hide the smallest value"],
      "Using boundaries that fall between possible data values (e.g., ending in .5 for whole-number data) ensures each value belongs to exactly one bar."),
    mc(p, "A histogram of 50 exam scores has bars with heights 0.10, 0.30, 0.40, 0.20 (relative frequencies). How many scores fell in the third interval?",
      ["20", "0.40", "4", "40"],
      "Relative frequency × n = 0.40 × 50 = 20 scores."),
    mc(p, "In a histogram, the bars touch each other because…",
      ["the data are continuous and the intervals cover the whole number line without gaps", "it saves space", "bar graphs and histograms are the same thing", "the frequencies must add to 1"],
      "Adjacent intervals share a boundary, so there is no gap between bars. Bar graphs of categorical data leave gaps."),
    mc(p, "A histogram has a long tail stretching to the right. Its shape is…",
      ["skewed right", "skewed left", "symmetric", "uniform"],
      "Skewness is named by the direction of the longer tail. A right-skewed distribution typically has mean > median."),
    mc(p, "What does a frequency polygon plot?",
      ["Points at the midpoint of each interval at height equal to its frequency, connected by lines", "The cumulative frequency at each interval's upper boundary", "Individual data values as dots", "Category names against counts"],
      "A frequency polygon is the line-graph cousin of the histogram; it is handy for overlaying two distributions."),
    mc(p, "Which graph is appropriate for showing a store's monthly sales over the last five years?",
      ["Time series graph", "Histogram", "Stem-and-leaf plot", "Bar graph of categories"],
      "A time series graph plots a measurement against time to reveal trends and seasonality."),
    tf(p, "The vertical axis of a histogram may show either frequency or relative frequency; the shape is the same either way.", true,
      "Relative frequency just rescales the heights by dividing by n, so the shape does not change."),
    order(p, "Order the steps for constructing a histogram.", [
      "Find the smallest and largest values",
      "Choose the number of bars and compute a convenient width",
      "Set the interval boundaries so no value lands on a boundary",
      "Count the frequency in each interval",
      "Draw touching bars with heights equal to the frequencies",
    ], "Boundaries are chosen before counting so every value belongs to exactly one interval."),
    mc(p, "Data: 2, 3, 3, 4, 7, 8, 9, 9, 9, 10 grouped into intervals 1.5–4.5, 4.5–7.5, 7.5–10.5. What is the frequency of the middle interval?",
      ["1", "4", "5", "3"],
      "Only the value 7 falls between 4.5 and 7.5. The first interval holds 2, 3, 3, 4 (four values) and the last holds 8, 9, 9, 9, 10 (five values)."),
  ]);

const l3 = lesson("u2.3", "2.3", "Measures of location: percentiles and quartiles",
  "Percentiles tell you where a value sits relative to the rest of the data. Quartiles split the data into fourths, and the interquartile range (IQR) measures the spread of the middle half and flags potential outliers.",
  ["The kth percentile: about k% of the data are at or below it.",
   "Q₁ = 25th percentile, Q₂ = median = 50th, Q₃ = 75th percentile.",
   "IQR = Q₃ − Q₁. Potential outliers lie below Q₁ − 1.5·IQR or above Q₃ + 1.5·IQR.",
   "Locate the kth percentile with position i = (k/100)(n + 1) on the ordered data; average the neighbors when i is not an integer.",
   "Percentile of a given value: (x + 0.5y)/n × 100, where x = number of values below it and y = number equal to it.",
   "Interpreting a percentile requires context: a low percentile is good for run times, bad for exam scores."],
  [
    G.quartilesIQR,
    G.quartilesIQR,
    G.outlierFence,
    G.percentileInterpretation,
    num(p, "Ordered data: 3, 5, 7, 8, 10, 12, 14, 15, 18. What is the median?", 10,
      "With n = 9 the median is the 5th value: 10.", { tolerance: 0 }),
    num(p, "For the same data (3, 5, 7, 8, 10, 12, 14, 15, 18), find Q₁.", 6,
      "The lower half (excluding the median) is 3, 5, 7, 8. Its median is (5 + 7)/2 = 6.", { tolerance: 0.01 }),
    num(p, "For the same data, find the IQR.", 8.5,
      "Upper half is 12, 14, 15, 18 with median (14 + 15)/2 = 14.5. IQR = 14.5 − 6 = 8.5.", { tolerance: 0.01 }),
    mc(p, "Your score on a standardized test is at the 88th percentile. Which statement is correct?",
      ["You scored higher than about 88% of test takers", "You answered 88% of the questions correctly", "88% of test takers scored higher than you", "Your score was 88 points"],
      "Percentiles describe relative standing, not the percentage of correct answers."),
    mc(p, "A data set has Q₁ = 40 and Q₃ = 60. A value of 95 is…",
      ["a potential outlier, since 95 > 60 + 1.5(20) = 90", "not an outlier, since it is within 2 IQRs", "impossible, because it exceeds Q₃", "exactly on the upper fence"],
      "IQR = 20, upper fence = Q₃ + 1.5·IQR = 90. Because 95 > 90, it is flagged as a potential outlier."),
    mc(p, "Which measure of location is least affected by an extreme value?",
      ["Median", "Mean", "Maximum", "Range"],
      "The median depends only on the order of values, so one extreme observation cannot pull it far. The mean, maximum, and range all shift."),
    tf(p, "The 50th percentile, the median, and the second quartile are all the same value.", true,
      "All three describe the point that splits the ordered data into two equal halves."),
    num(p, "Using i = (k/100)(n + 1) with n = 19 data values, at which position is the 30th percentile located?", 6,
      "i = (30/100)(20) = 6, an integer, so the 30th percentile is the 6th value in the ordered list.", { tolerance: 0 }),
    G.percentileOfValue, G.percentileOfValue,
    num(p, "Ordered data: 2, 4, 5, 5, 7, 8, 9, 9, 9, 11, 12, 15. What is the percentile of the value 9? (Nearest whole percent.)", 63,
      "x = 6 values are below 9 and y = 3 values equal 9. Percentile = (x + 0.5y)/n × 100 = (6 + 1.5)/12 × 100 = 62.5, which rounds to the 63rd percentile.", { tolerance: 1 }),
    num(p, "With n = 29 ordered values, use i = (k/100)(n + 1) to find the position of the 90th percentile.", 27,
      "i = (90/100)(30) = 27, an integer, so the 90th percentile is the 27th value in the ordered list.", { tolerance: 0 }),
    num(p, "With n = 12 ordered values, i = (k/100)(n + 1) for the 40th percentile gives i = 5.2. What do you do?", 5.2,
      "Since i is not an integer, the 40th percentile is the average of the 5th and 6th values (the values at positions on either side of 5.2).", { tolerance: 0.01 }),
  ]);

const l4 = lesson("u2.4", "2.4", "Box plots",
  "A box plot (box-and-whisker plot) draws the five-number summary: minimum, Q₁, median, Q₃, and maximum. The box shows the middle 50% of the data; the whiskers show the rest.",
  ["Five-number summary: min, Q₁, median, Q₃, max.",
   "The box spans Q₁ to Q₃; a line inside marks the median.",
   "Each section (whisker or half-box) contains about 25% of the data, regardless of its length.",
   "A long whisker or half-box means the data are spread out there; a short one means they are bunched.",
   "Box plots are great for comparing several groups side by side."],
  [
    G.quartilesIQR, G.outlierFence,
    mc(p, "A box plot has min = 10, Q₁ = 20, median = 25, Q₃ = 40, max = 70. Roughly what percent of the data lie between 20 and 40?",
      ["50%", "25%", "75%", "It depends on the data"],
      "The box, from Q₁ to Q₃, always contains the middle half of the data."),
    mc(p, "In that same plot, which quarter of the data is the most spread out?",
      ["The top 25% (from 40 to 70)", "The bottom 25% (from 10 to 20)", "From 20 to 25", "From 25 to 40"],
      "Each quarter has the same number of values; the widest interval (30 units, from Q₃ to max) is the most spread out."),
    mc(p, "Two classes' test scores are shown as box plots. Class A: median 78, IQR 10. Class B: median 78, IQR 25. What can you conclude?",
      ["Both classes have the same typical score, but Class B's scores are more spread out", "Class B scored higher on average", "Class A has more students", "Class A has outliers"],
      "The medians match, so typical performance is similar; the larger IQR means Class B's middle half is more variable."),
    order(p, "Arrange the five-number summary in the order it appears from left to right on a box plot.", [
      "Minimum", "First quartile", "Median", "Third quartile", "Maximum",
    ], "Box plots run from the smallest value on the left to the largest on the right."),
    tf(p, "If the median line is closer to Q₁ than to Q₃, the data between the median and Q₃ are more spread out than the data between Q₁ and the median.", true,
      "Each half of the box holds 25% of the data; the wider half is the more spread out one."),
    num(p, "Data: 4, 6, 7, 9, 11, 13, 15, 20. What is the maximum of the five-number summary?", 20,
      "The maximum is simply the largest value.", { tolerance: 0 }),
    num(p, "For the data 4, 6, 7, 9, 11, 13, 15, 20, what is Q₃?", 14,
      "The upper half is 11, 13, 15, 20; its median is (13 + 15)/2 = 14.", { tolerance: 0.01 }),
    mc(p, "When can a box plot have no visible whisker on one side?",
      ["When the minimum (or maximum) equals the corresponding quartile", "Never", "When the data are symmetric", "When the median equals the mean"],
      "If, say, the smallest 25% of values are all equal to Q₁, the left whisker has zero length."),
    mc(p, "Which of the following is NOT shown directly on a standard box plot?",
      ["The mean", "The median", "The first quartile", "The maximum"],
      "Box plots are built from the five-number summary, which does not include the mean."),
    mc(p, "Two box plots drawn on the same axis compare the test scores of one class before and after a review session, using the same students each time. This kind of data is called…",
      ["a paired data set (two values for each individual)", "a stratified sample", "a frequency table", "a bimodal distribution"],
      "A paired data set has two measurements on each individual. Side-by-side box plots are a good way to compare the two sets of values at a glance."),
  ]);

const l5 = lesson("u2.5", "2.5", "Measures of center: mean, median, and mode",
  "The mean is the arithmetic average, the median is the middle value, and the mode is the most frequent value. Each is a way to describe a 'typical' value, and each reacts differently to outliers.",
  ["Mean x̄ = Σx / n. For a frequency table, x̄ = Σ(x·f) / Σf.",
   "Grouped data (intervals only): use each interval's midpoint m and estimate x̄ ≈ Σ(f·m) / Σf.",
   "Median: middle value of the ordered data (average of the two middle values when n is even).",
   "Mode: most frequent value; a data set can have no mode, one mode, or several.",
   "The mean is sensitive to outliers; the median is resistant.",
   "The law of large numbers: as n grows, the sample mean tends toward the population mean μ."],
  [
    G.meanOfData, G.medianOfData, G.modeOfData,
    num(p, "Five friends' ages are 21, 22, 22, 24, and 61. What is the mean age?", 30,
      "(21 + 22 + 22 + 24 + 61)/5 = 150/5 = 30.", { tolerance: 0.01 }),
    num(p, "For the ages 21, 22, 22, 24, 61, what is the median?", 22,
      "The ordered middle (3rd) value is 22. Notice how much smaller it is than the mean of 30.", { tolerance: 0 }),
    mc(p, "For the ages 21, 22, 22, 24, 61, which measure of center best describes the typical age?",
      ["The median, because the outlier 61 inflates the mean", "The mean, because it uses every value", "The mode, because it is the smallest", "The range"],
      "One extreme value drags the mean up to 30 even though four of the five friends are in their early twenties. The median (22) resists the outlier."),
    num(p, "A frequency table shows: value 2 (frequency 3), value 5 (frequency 4), value 8 (frequency 3). What is the mean?", 5,
      "x̄ = (2·3 + 5·4 + 8·3)/(3 + 4 + 3) = (6 + 20 + 24)/10 = 50/10 = 5.", { tolerance: 0.01 }),
    mc(p, "Which is a correct statement about the mode?",
      ["A data set can have more than one mode", "The mode is always equal to the median", "Every data set has exactly one mode", "The mode must be a value in the middle of the data"],
      "If two values tie for the highest frequency the data are bimodal. If no value repeats, there is no mode."),
    mc(p, "A student's exam scores are 70, 80, and 90. What score on a fourth exam would make the mean 85?",
      ["100", "85", "95", "90"],
      "The four scores must total 4 × 85 = 340; 340 − (70 + 80 + 90) = 100."),
    tf(p, "The law of large numbers says that a larger sample tends to have a sample mean closer to the population mean.", true,
      "As n increases, x̄ is more and more likely to be close to μ. It does not say a streak of lows must be 'balanced' by highs."),
    mc(p, "House prices in a neighborhood are mostly around $300,000 but one mansion sold for $5 million. Which statement is true?",
      ["The mean is much larger than the median", "The median is much larger than the mean", "The mean and median are equal", "The mode is $5 million"],
      "A single very large value pulls the mean up but barely moves the median."),
    text(p, "Which measure of center is found by adding all values and dividing by how many there are?", ["mean", "the mean", "average", "arithmetic mean"],
      "That is the mean (arithmetic average), written x̄ for a sample and μ for a population."),
    G.groupedMean, G.groupedMean,
    mc(p, "A table gives only intervals and frequencies (e.g., 50–56.5: 3 students, 56.5–62.5: 5 students, …). How can the mean be estimated?",
      ["Use each interval's midpoint as the value, multiply by its frequency, add, and divide by the total frequency", "Average the lower boundaries", "Take the median of the frequencies", "It cannot be estimated without the raw data"],
      "The midpoint (lower + upper)/2 stands in for every value in the interval, giving x̄ ≈ Σ(f·m)/Σf."),
  ]);

const l6 = lesson("u2.6", "2.6", "Skewness and the mean, median, and mode",
  "The shape of a distribution tells you how its measures of center relate. In a symmetric distribution the mean, median, and mode line up; skewness pulls the mean toward the long tail.",
  ["Symmetric: mean ≈ median ≈ mode.",
   "Skewed right (long right tail): mode < median < mean, typically.",
   "Skewed left (long left tail): mean < median < mode, typically.",
   "The mean is pulled toward the tail because extreme values affect it most."],
  [
    G.meanOfData, G.medianOfData,
    mc(p, "A distribution of incomes has a long tail to the right. Which ordering is most likely?",
      ["mode < median < mean", "mean < median < mode", "mean = median = mode", "median < mode < mean"],
      "Right skew pulls the mean toward the high tail; the mode stays at the peak on the left."),
    mc(p, "For a data set, the mean is 48, the median is 55, and the mode is 60. The distribution is most likely…",
      ["skewed left", "skewed right", "symmetric", "uniform"],
      "Mean < median < mode is the signature of a left skew: a long tail of low values drags the mean down."),
    mc(p, "In a perfectly symmetric, single-peaked distribution…",
      ["the mean, median, and mode are all equal", "the mean is larger than the median", "the mode is undefined", "the median is larger than the mean"],
      "Symmetry puts the balance point (mean), the middle (median), and the peak (mode) at the same place."),
    tf(p, "In a right-skewed distribution, the median is typically greater than the mean.", false,
      "Right skew usually gives mean > median because the tail of large values inflates the mean."),
    classify(p, "Match each data set to its likely shape.", ["Skewed right", "Skewed left", "Symmetric"], [
      ["Number of children per household in a country", "Skewed right"],
      ["Age at retirement (most retire near 65, a few much earlier)", "Skewed left"],
      ["Heights of adult women", "Symmetric"],
      ["Time spent waiting on hold (usually short, occasionally very long)", "Skewed right"],
    ], "Think about where the rare, extreme values are: to the right (high) means right skew, to the left (low) means left skew."),
    mc(p, "Data: 1, 2, 2, 3, 3, 3, 4, 4, 5, 20. Which describes the shape?",
      ["Skewed right because of the value 20", "Skewed left because most values are small", "Symmetric", "Bimodal"],
      "A single high value (20) creates a long right tail. Mean = 4.7 while the median is 3."),
    mc(p, "Which measure of center is most appropriate to report for a strongly skewed distribution?",
      ["Median", "Mean", "Mode", "Range"],
      "The median resists the extreme values in the tail and better represents a typical observation."),
    mc(p, "A histogram's peak is on the right and its tail extends to the left. Its skewness is…",
      ["left (negative)", "right (positive)", "zero", "undefined"],
      "Skew is named for the direction of the tail, not the peak. A tail to the left means left skew."),
  ]);

const l7 = lesson("u2.7", "2.7", "Measures of spread: variance and standard deviation",
  "Spread describes how far values typically fall from the center. The standard deviation is the most important measure: it is the typical distance from the mean, in the same units as the data. z-scores use it to compare values from different distributions.",
  ["Range = max − min. IQR = Q₃ − Q₁.",
   "Sample: s = √( Σ(x − x̄)² / (n − 1) ), or with a frequency table s = √( Σ f(x − x̄)² / (n − 1) ). Population: σ = √( Σ(x − μ)² / N ).",
   "Standard deviation is never negative and is 0 only when all values are identical.",
   "z = (x − mean)/SD measures how many SDs a value is from the mean.",
   "Chebyshev: at least 75% of data within 2 SDs of the mean for ANY distribution; for bell shapes, about 95%."],
  [
    G.sampleSDOfData, G.zScoreFromData, G.valueFromZ,
    num(p, "Sample data: 2, 4, 4, 4, 5, 5, 7, 9. The mean is 5. Find the sample variance s². (Round to 2 decimals.)", 4.571,
      "Squared deviations: 9, 1, 1, 1, 0, 0, 4, 16 (sum 32). s² = 32/(8 − 1) = 4.571.", { tolerance: 0.02 }),
    num(p, "For the same data (s² ≈ 4.571), find the sample standard deviation s. (2 decimals.)", 2.138,
      "s = √4.571 ≈ 2.14.", { tolerance: 0.02 }),
    mc(p, "Why does the sample variance divide by n − 1 instead of n?",
      ["Dividing by n − 1 makes s² an unbiased estimate of the population variance", "Because one data value is always discarded", "To make the variance smaller", "It is a historical accident with no reason"],
      "Deviations are measured from x̄ rather than the unknown μ, which makes them slightly too small on average; dividing by n − 1 corrects this."),
    mc(p, "Two classes take the same exam. Class A: mean 75, SD 3. Class B: mean 75, SD 12. Which statement is correct?",
      ["Scores in Class B vary much more from student to student", "Class B performed better", "Class A has more students", "The classes have identical score distributions"],
      "Same center, different spread: a larger SD means scores are more dispersed around 75."),
    mc(p, "Ana scored 82 on a test with mean 70 and SD 8. Ben scored 90 on a test with mean 80 and SD 10. Who did relatively better?",
      ["Ana: z = 1.5 versus Ben's z = 1.0", "Ben, because 90 > 82", "They did equally well", "Ben: z = 1.5 versus Ana's z = 1.0"],
      "z_Ana = (82 − 70)/8 = 1.5; z_Ben = (90 − 80)/10 = 1.0. Ana is more standard deviations above her class mean."),
    tf(p, "The standard deviation can be negative when most values are below the mean.", false,
      "SD is a square root of an average of squared deviations, so it is always ≥ 0."),
    mc(p, "By Chebyshev's Rule, at least what percentage of ANY data set lies within 2 standard deviations of the mean?",
      ["75%", "95%", "68%", "50%"],
      "Chebyshev guarantees at least 1 − 1/k² of the data within k SDs: for k = 2 that is 75%. Bell-shaped data do better (about 95%)."),
    mc(p, "If every value in a data set is increased by 10, what happens to the standard deviation?",
      ["It stays the same", "It increases by 10", "It increases by √10", "It doubles"],
      "Shifting all values moves the mean but leaves every deviation from the mean unchanged, so the SD is unchanged."),
    mc(p, "A value has z = −2.3. This means the value is…",
      ["2.3 standard deviations below the mean", "2.3 units below the mean", "negative", "2.3 standard deviations above the mean"],
      "The sign of z gives the direction (below the mean), and its magnitude counts standard deviations."),
    num(p, "The range of the data 14, 3, 27, 9, 18 is:", 24,
      "Range = max − min = 27 − 3 = 24.", { tolerance: 0 }),
    num(p, "A frequency table lists value 3 (frequency 2), value 5 (frequency 3), value 8 (frequency 1). Estimate the sample mean first: what is x̄? (2 decimals.)", 5,
      "x̄ = Σ(x·f)/Σf = (3·2 + 5·3 + 8·1)/6 = 30/6 = 5.", { tolerance: 0.011 }),
    num(p, "Same table (3 ×2, 5 ×3, 8 ×1; x̄ = 5). Find the sample standard deviation using s = √(Σ f(x − x̄)²/(n − 1)). (2 decimals.)", 1.84,
      "Σ f(x − x̄)² = 2(−2)² + 3(0)² + 1(3)² = 8 + 0 + 9 = 17. With n − 1 = 6 − 1 = 5, s = √(17/5) = √3.4 ≈ 1.84.", { tolerance: 0.06 }),
  ]);

export const unit2 = unit(2, "Descriptive Statistics", "Graphs, center, spread, and shape: how to summarize a data set.", "📊", "#1cb0f6", [l1, l2, l3, l4, l5, l6, l7]);
