import { mc, tf, num, text, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u3";

const l1 = lesson("u3.1", "3.1", "Probability terminology",
  "Probability measures the long-run relative frequency of an outcome. The sample space lists everything that can happen; events are subsets of it. Conditional probability updates the chance of an event given that another has occurred.",
  ["Experiment: a chance process. Outcome: one result. Sample space S: all outcomes. Event: a subset of S.",
   "0 ≤ P(A) ≤ 1; P(S) = 1. Equally likely outcomes: P(A) = (outcomes in A)/(outcomes in S).",
   "A OR B: either or both. A AND B: both. A′ (complement): not A, with P(A) + P(A′) = 1.",
   "Conditional probability P(A|B) = P(A AND B)/P(B): the chance of A within the reduced sample space B.",
   "Law of large numbers: relative frequency approaches probability as trials increase."],
  [
    G.basicProbability, G.basicProbability, G.complementRule, G.conditionalProbability,
    mc(p, "Two coins are flipped. What is the sample space?",
      ["{HH, HT, TH, TT}", "{H, T}", "{HH, TT}", "{0, 1, 2}"],
      "Each coin has two outcomes, giving 2 × 2 = 4 equally likely ordered outcomes."),
    num(p, "Two fair coins are flipped. What is P(exactly one head)? (Enter a decimal.)", 0.5,
      "HT and TH are the two favorable outcomes out of four: 2/4 = 0.5.", { tolerance: 0.001 }),
    mc(p, "Which number cannot be a probability?",
      ["1.2", "0", "0.999", "1"],
      "Probabilities live between 0 (impossible) and 1 (certain). 1.2 is outside that range."),
    mc(p, "Let A = a rolled die shows an even number and B = it shows a number greater than 3. What is A AND B?",
      ["{4, 6}", "{2, 4, 5, 6}", "{4, 5, 6}", "{2, 4, 6}"],
      "AND means the outcome must satisfy both conditions: even AND greater than 3 gives 4 and 6."),
    mc(p, "With A = even and B = greater than 3 on a die, what is A OR B?",
      ["{2, 4, 5, 6}", "{4, 6}", "{1, 3}", "{4, 5, 6}"],
      "OR includes outcomes in A, in B, or in both: {2, 4, 6} ∪ {4, 5, 6} = {2, 4, 5, 6}."),
    num(p, "A card is drawn from a standard deck. Given that it is a face card (J, Q, K), what is the probability it is a king? (4 decimals.)", 0.3333,
      "Conditioning on 'face card' shrinks the sample space to 12 cards, 4 of which are kings: 4/12 = 0.3333.", { tolerance: 0.001 }),
    tf(p, "If P(A) = 0.3, then P(A′) = 0.7.", true,
      "The complement rule: P(A′) = 1 − P(A) = 0.7."),
    mc(p, "You flip a fair coin 10 times and get 8 heads. According to the law of large numbers…",
      ["over many more flips the proportion of heads will get close to 0.5", "the next few flips are more likely to be tails to even things out", "the coin must be biased", "the probability of heads is now 0.8"],
      "Probability describes the long-run proportion. Short runs can be lopsided; the coin has no memory."),
    text(p, "What is the term for the set of all possible outcomes of an experiment?", ["sample space", "the sample space"],
      "The sample space, usually written S, lists every possible outcome."),
  ]);

const l2 = lesson("u3.2", "3.2", "Independent and mutually exclusive events",
  "Two special relationships between events: independent events do not influence each other, while mutually exclusive events cannot happen together. They are not the same thing, and confusing them is one of the most common probability mistakes.",
  ["Independent: P(A|B) = P(A), equivalently P(A AND B) = P(A)·P(B).",
   "Mutually exclusive: P(A AND B) = 0; the events share no outcomes.",
   "Events with positive probability that are mutually exclusive are NOT independent.",
   "Sampling with replacement gives independent draws; without replacement, draws are dependent.",
   "To check independence, verify one of the equivalent equations; do not assume."],
  [
    G.independenceCheck, G.independenceCheck,
    mc(p, "A card is drawn, replaced, the deck shuffled, and a second card drawn. Are the two draws independent?",
      ["Yes, because replacing the card restores the deck to its original state", "No, because the same card could be drawn twice", "No, because cards are never independent", "Only if the first card was a face card"],
      "With replacement, the second draw has the same probabilities regardless of the first; that is independence."),
    mc(p, "Two cards are drawn WITHOUT replacement. Are the events 'first is an ace' and 'second is an ace' independent?",
      ["No: the first draw changes the deck, so P(second ace | first ace) = 3/51 ≠ 4/52", "Yes: each card is equally likely", "Yes: aces are independent of each other", "No: because there are only four aces"],
      "Without replacement, the probability of the second event depends on the first outcome, so the events are dependent."),
    mc(p, "Events A and B are mutually exclusive with P(A) = 0.4 and P(B) = 0.3. What is P(A AND B)?",
      ["0", "0.12", "0.7", "0.1"],
      "Mutually exclusive means they cannot both occur, so P(A AND B) = 0."),
    mc(p, "Events A and B are mutually exclusive with P(A) = 0.4 and P(B) = 0.3. Are they independent?",
      ["No, because P(A AND B) = 0 but P(A)P(B) = 0.12", "Yes, because they cannot influence each other", "Yes, because P(A) ≠ P(B)", "Cannot be determined"],
      "If A happens, B definitely does not, so knowing A changes the chance of B. Mutually exclusive events with positive probabilities are always dependent."),
    tf(p, "'Independent' and 'mutually exclusive' mean the same thing.", false,
      "Independent means one event gives no information about the other. Mutually exclusive means they cannot both happen, which is very strong information."),
    classify(p, "Classify each pair of events.", ["Mutually exclusive", "Independent", "Neither"], [
      ["Rolling a 2 and rolling a 5 on one die roll", "Mutually exclusive"],
      ["Getting heads on a first coin flip and heads on a second flip", "Independent"],
      ["Being a senior and being 17 years old (in a typical high school)", "Neither"],
      ["Drawing a heart and drawing a spade on a single draw", "Mutually exclusive"],
    ], "Two outcomes of the same single trial are mutually exclusive; separate trials with no influence are independent; overlapping, related characteristics are neither."),
    num(p, "P(A) = 0.5 and P(B) = 0.6, and A and B are independent. What is P(A AND B)?", 0.3,
      "For independent events, P(A AND B) = P(A)·P(B) = 0.5 × 0.6 = 0.30.", { tolerance: 0.001 }),
    mc(p, "If P(A|B) = P(A), then A and B are…",
      ["independent", "mutually exclusive", "complementary", "identical"],
      "Knowing B occurred does not change the probability of A; that is the definition of independence."),
    mc(p, "A and B are independent, P(A) = 0.2, P(B) = 0.5. What is P(A|B)?",
      ["0.2", "0.1", "0.5", "0.7"],
      "Independence means the conditional probability equals the unconditional one: P(A|B) = P(A) = 0.2."),
  ]);

const l3 = lesson("u3.3", "3.3", "The multiplication and addition rules",
  "Two rules do most of the work in probability. The multiplication rule finds the probability that both events happen; the addition rule finds the probability that at least one happens.",
  ["Multiplication rule: P(A AND B) = P(B)·P(A|B). If independent, P(A AND B) = P(A)·P(B).",
   "Addition rule: P(A OR B) = P(A) + P(B) − P(A AND B).",
   "If mutually exclusive, P(A OR B) = P(A) + P(B) because P(A AND B) = 0.",
   "Subtracting P(A AND B) avoids double-counting the overlap."],
  [
    G.additionRule, G.additionRule, G.conditionalProbability,
    num(p, "In a class, 60% play a sport, 40% play an instrument, and 25% do both. What is the probability a randomly chosen student does at least one? (2 decimals.)", 0.75,
      "P(S OR I) = 0.60 + 0.40 − 0.25 = 0.75.", { tolerance: 0.006 }),
    num(p, "With 60% sport, 40% instrument, 25% both, what is the probability a student does neither? (2 decimals.)", 0.25,
      "P(neither) = 1 − P(at least one) = 1 − 0.75 = 0.25.", { tolerance: 0.006 }),
    num(p, "A bag has 4 red and 6 blue marbles. Two are drawn without replacement. What is P(both red)? (4 decimals.)", 0.1333,
      "P(R₁)·P(R₂|R₁) = (4/10)(3/9) = 12/90 = 0.1333.", { tolerance: 0.001 }),
    num(p, "Same bag (4 red, 6 blue), but the first marble is replaced before the second draw. What is P(both red)? (2 decimals.)", 0.16,
      "With replacement the draws are independent: (4/10)(4/10) = 0.16.", { tolerance: 0.006 }),
    mc(p, "Why does the addition rule subtract P(A AND B)?",
      ["Because outcomes in both A and B would otherwise be counted twice", "Because probabilities can never exceed 0.5", "To make the answer smaller than P(A)", "It is only subtracted for independent events"],
      "P(A) and P(B) each include the overlap; subtracting it once leaves each outcome counted exactly once."),
    mc(p, "P(A) = 0.5, P(B) = 0.7, and P(A OR B) = 0.9. What is P(A AND B)?",
      ["0.3", "0.35", "0.2", "1.2"],
      "Rearranging the addition rule: P(A AND B) = P(A) + P(B) − P(A OR B) = 0.5 + 0.7 − 0.9 = 0.3."),
    mc(p, "A fair die is rolled twice. What is the probability of getting a 6 on the first roll OR a 6 on the second roll?",
      ["11/36", "12/36", "1/36", "2/36"],
      "P(6₁ OR 6₂) = 1/6 + 1/6 − (1/6)(1/6) = 12/36 − 1/36 = 11/36."),
    tf(p, "For mutually exclusive events, P(A OR B) = P(A) + P(B).", true,
      "There is no overlap to subtract, so the probabilities simply add."),
    mc(p, "A password is generated by choosing a random letter (26 options) followed by a random digit (10 options), independently. What is P(letter is a vowel AND digit is odd)?",
      ["(5/26)(5/10) ≈ 0.096", "5/26 + 5/10", "(5/26)(1/10)", "5/36"],
      "The choices are independent, so multiply: P(vowel)·P(odd) = (5/26)(5/10) ≈ 0.096."),
  ]);

const l4 = lesson("u3.4", "3.4", "Contingency tables",
  "A contingency table (two-way table) cross-classifies data by two variables. Row and column totals let you read off marginal, joint, and conditional probabilities and test for independence.",
  ["Joint probability: a single cell divided by the grand total.",
   "Marginal probability: a row or column total divided by the grand total.",
   "Conditional probability P(A|B): the cell count divided by the total of the row or column B.",
   "Check independence by comparing P(A|B) with P(A)."],
  [
    G.contingencyTable, G.contingencyTable, G.contingencyTable,
    num(p, "Of 200 customers: 80 bought coffee and a pastry, 60 bought only coffee, 30 bought only a pastry, 30 bought neither. What is P(coffee)? (2 decimals.)", 0.7,
      "Coffee buyers = 80 + 60 = 140. 140/200 = 0.70.", { tolerance: 0.006 }),
    num(p, "Using the same customers, what is P(pastry | coffee)? (3 decimals.)", 0.571,
      "Among the 140 coffee buyers, 80 also bought a pastry: 80/140 = 0.571.", { tolerance: 0.002 }),
    mc(p, "Using the same customers, are 'buys coffee' and 'buys pastry' independent?",
      ["No: P(pastry) = 0.55 but P(pastry | coffee) ≈ 0.57", "Yes: both are common purchases", "Yes: P(coffee AND pastry) > 0", "No: because some customers bought neither"],
      "Pastry buyers = 80 + 30 = 110, so P(pastry) = 0.55, which differs from P(pastry | coffee) = 0.571. Knowing someone bought coffee changes the pastry probability, so the events are dependent."),
    mc(p, "In a two-way table, the number in the bottom-right corner is usually…",
      ["the grand total (sample size)", "the largest cell", "the probability of both events", "always 100"],
      "Row totals and column totals both add to the grand total in the corner."),
    mc(p, "A table classifies 500 voters by party (3 rows) and age group (4 columns). How many cells (not counting totals) does it have?",
      ["12", "7", "500", "3"],
      "3 rows × 4 columns = 12 joint cells."),
    tf(p, "To find P(A | B) from a contingency table, divide the A-and-B cell by the grand total.", false,
      "Divide by the total for B (the row or column you are conditioning on), not the grand total. Dividing by the grand total gives the joint probability P(A AND B)."),
  ]);

const l5 = lesson("u3.5", "3.5", "Tree and Venn diagrams",
  "Tree diagrams organize multi-stage experiments: multiply along a branch for AND, add across branches for OR. Venn diagrams show overlapping events as circles, making unions, intersections, and complements visual.",
  ["Tree: branch probabilities at each stage; multiply along a path; the paths' probabilities add to 1.",
   "Without replacement, second-stage probabilities depend on the first stage.",
   "Venn: overlap = A AND B; everything inside either circle = A OR B; outside = neither.",
   "Mutually exclusive events appear as non-overlapping circles."],
  [
    num(p, "An urn has 3 white and 2 black balls. Two are drawn without replacement. Using a tree diagram, find P(white then black). (Enter a decimal.)", 0.3,
      "P(W₁) = 3/5, P(B₂|W₁) = 2/4. Multiply along the branch: (3/5)(2/4) = 6/20 = 0.30.", { tolerance: 0.001 }),
    num(p, "Same urn (3 white, 2 black), two draws without replacement. Find P(one of each color). (Enter a decimal.)", 0.6,
      "Add the two branches WB and BW: (3/5)(2/4) + (2/5)(3/4) = 0.3 + 0.3 = 0.6.", { tolerance: 0.001 }),
    num(p, "Same urn, but now WITH replacement. Find P(both black). (2 decimals.)", 0.16,
      "With replacement the second draw is unchanged: (2/5)(2/5) = 4/25 = 0.16.", { tolerance: 0.006 }),
    mc(p, "On a tree diagram, how do you find the probability of a particular sequence of outcomes?",
      ["Multiply the probabilities along the path", "Add the probabilities along the path", "Divide the last probability by the first", "Take the largest probability on the path"],
      "Each branch is a conditional probability; the multiplication rule chains them together."),
    mc(p, "In a Venn diagram, the region inside circle A but outside circle B represents…",
      ["A AND B′ (A but not B)", "A OR B", "A AND B", "Neither A nor B"],
      "Being inside A and outside B is exactly 'A and not B'."),
    num(p, "In a Venn diagram of 100 students, 45 are in circle Math, 30 in circle Art, and 10 in the overlap. How many students are outside both circles?", 35,
      "Inside at least one circle: 45 + 30 − 10 = 65. Outside both: 100 − 65 = 35.", { tolerance: 0 }),
    mc(p, "Two circles in a Venn diagram do not overlap. The events are…",
      ["mutually exclusive", "independent", "complementary", "equally likely"],
      "No overlap means no outcome belongs to both events: P(A AND B) = 0, i.e., mutually exclusive."),
    tf(p, "The probabilities at the ends of all the branches of a complete tree diagram add up to 1.", true,
      "The final branches list every possible outcome of the full experiment, so their probabilities must total 1."),
    mc(p, "A quality test has two stages. Stage 1 passes 90% of items. Of those that pass, 80% also pass stage 2. What fraction of items pass both stages?",
      ["0.72", "0.85", "1.70", "0.10"],
      "Multiply along the pass-pass branch: 0.90 × 0.80 = 0.72."),
    order(p, "Order the steps for finding P(A OR B) from a Venn diagram with counts.", [
      "Find the count in the overlap (A AND B)",
      "Find the total count in circle A and in circle B",
      "Add the two circle totals and subtract the overlap",
      "Divide by the grand total",
    ], "This is the addition rule carried out with counts."),
    match(p, "Match each Venn region to its probability expression.", [
      ["Overlap of the circles", "P(A AND B)"],
      ["Everything inside either circle", "P(A OR B)"],
      ["Everything outside both circles", "1 − P(A OR B)"],
      ["Inside B only", "P(B AND A′)"],
    ], "Reading Venn regions correctly turns pictures into formulas."),
  ]);

export const unit3 = unit(3, "Probability Topics", "The language and rules of chance: events, independence, and the addition and multiplication rules.", "🎲", "#ff9600", [l1, l2, l3, l4, l5]);
