import { mc, tf, num, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u4";

const l1 = lesson("u4.1", "4.1", "Probability distributions for discrete random variables",
  "A discrete random variable takes countable values, and its probability distribution function (PDF) lists each value with its probability. Two rules: every probability is between 0 and 1, and they all add to 1.",
  ["Random variable X: a numerical outcome of a chance process. Lowercase x is a specific value.",
   "A discrete PDF is a table or formula giving P(X = x) for each x.",
   "0 ≤ P(x) ≤ 1 for every x, and ΣP(x) = 1.",
   "Read probabilities of ranges by adding table entries: P(X ≥ 2) = P(2) + P(3) + …"],
  [
    G.missingProbability, G.missingProbability,
    mc(p, "Which of these is a valid probability distribution for X?",
      ["P(0)=0.2, P(1)=0.5, P(2)=0.3", "P(0)=0.4, P(1)=0.4, P(2)=0.4", "P(0)=0.7, P(1)=−0.1, P(2)=0.4", "P(0)=0.5, P(1)=0.3"],
      "Each probability must be between 0 and 1 and the total must be exactly 1. Only the first option satisfies both."),
    num(p, "X = number of defective items in a box. P(0) = 0.6, P(1) = 0.25, P(2) = ?, P(3) = 0.05. Find P(2).", 0.1,
      "The probabilities must sum to 1: 1 − (0.6 + 0.25 + 0.05) = 0.10.", { tolerance: 0.001 }),
    num(p, "With P(0) = 0.6, P(1) = 0.25, P(2) = 0.10, P(3) = 0.05, find P(X ≥ 1). (2 decimals.)", 0.4,
      "P(X ≥ 1) = 1 − P(0) = 0.40, or add 0.25 + 0.10 + 0.05.", { tolerance: 0.006 }),
    num(p, "Same distribution: find P(X < 2). (2 decimals.)", 0.85,
      "P(X < 2) = P(0) + P(1) = 0.60 + 0.25 = 0.85.", { tolerance: 0.006 }),
    mc(p, "Which of the following is a discrete random variable?",
      ["The number of emails you receive in a day", "The exact time you wait for a bus", "The weight of a randomly chosen apple", "The temperature at noon"],
      "Counts (emails) are discrete. Time, weight, and temperature are measured on a continuum."),
    mc(p, "In the notation P(X = x), what is the difference between X and x?",
      ["X is the random variable; x is one specific value it can take", "They are the same thing", "X is a sample; x is a population", "x is the probability"],
      "Capital letters name the random variable; lowercase letters denote particular values."),
    tf(p, "In a discrete probability distribution, one value can have probability exactly 0.", true,
      "A probability of 0 is allowed (though such a value is usually omitted from the table). The rule is 0 ≤ P(x) ≤ 1."),
    mc(p, "A game pays $5 with probability 0.1, $1 with probability 0.3, and $0 otherwise. What is P(win nothing)?",
      ["0.6", "0.4", "0.1", "0.3"],
      "Probabilities sum to 1: 1 − 0.1 − 0.3 = 0.6."),
    classify(p, "Sort each random variable as discrete or continuous.", ["Discrete", "Continuous"], [
      ["Number of heads in 10 coin flips", "Discrete"],
      ["Length of a phone call", "Continuous"],
      ["Number of customers in line", "Discrete"],
      ["Amount of water in a bottle", "Continuous"],
    ], "If you count it, it is discrete; if you measure it, it is continuous."),
  ]);

const l2 = lesson("u4.2", "4.2", "Expected value and standard deviation",
  "The expected value (mean) of a discrete random variable is the long-run average outcome: a weighted average of the values with probabilities as weights. The standard deviation measures how much outcomes vary around it.",
  ["Mean of a probability distribution: μ = E(X) = Σ x·P(x).",
   "Standard deviation of a probability distribution: σ² = Σ (x − μ)²·P(x), and σ = √σ².",
   "Expected value of a game = expected winnings; a fair game has expected value 0.",
   "Expected value need not be a possible outcome (e.g., 2.3 children)."],
  [
    G.expectedValue, G.expectedValue,
    num(p, "A raffle sells 1,000 tickets at $2 each. One ticket wins $1,000. What is the expected value of buying one ticket, in dollars?", -1,
      "Net outcomes: win $998 with probability 0.001, lose $2 with probability 0.999. E = 998(0.001) + (−2)(0.999) = 0.998 − 1.998 = −$1.00. Equivalently, expected prize $1 minus cost $2.", { tolerance: 0.01 }),
    num(p, "X has P(1) = 0.5, P(2) = 0.3, P(3) = 0.2. Find μ. (1 decimal.)", 1.7,
      "μ = 1(0.5) + 2(0.3) + 3(0.2) = 0.5 + 0.6 + 0.6 = 1.7.", { tolerance: 0.01 }),
    num(p, "For X with P(1) = 0.5, P(2) = 0.3, P(3) = 0.2 and μ = 1.7, find σ. (2 decimals.)", 0.78,
      "σ² = (1−1.7)²(0.5) + (2−1.7)²(0.3) + (3−1.7)²(0.2) = 0.245 + 0.027 + 0.338 = 0.61, so σ = √0.61 ≈ 0.78.", { tolerance: 0.02 }),
    mc(p, "A game has expected value −$0.50 per play. What does this mean?",
      ["Over many plays you would lose an average of 50 cents per play", "You lose exactly 50 cents each time you play", "You cannot win", "The game costs 50 cents"],
      "Expected value is a long-run average; individual plays vary, some winning and some losing."),
    mc(p, "A game is called fair when…",
      ["its expected value is 0", "the player wins half the time", "the prizes are all equal", "the probabilities are all equal"],
      "A fair game neither favors the player nor the house in the long run: E(X) = 0."),
    tf(p, "The expected value of a random variable must be one of the values the variable can actually take.", false,
      "E(X) is an average. The expected number of children in a household might be 1.9 even though no household has 1.9 children."),
    mc(p, "An insurance company charges $300 for a policy that pays $20,000 with probability 0.01. What is the company's expected profit per policy?",
      ["$100", "$300", "−$100", "$200"],
      "Expected payout = 20,000 × 0.01 = $200. Profit = 300 − 200 = $100 per policy on average."),
    mc(p, "Two investments have the same expected return, but investment A has a larger standard deviation. Investment A is…",
      ["riskier (more variable outcomes)", "guaranteed to return more", "guaranteed to return less", "impossible to compare"],
      "Standard deviation measures variability of outcomes; more variability means more risk."),
    order(p, "Order the steps to compute the standard deviation of a discrete random variable.", [
      "Compute μ = Σ x·P(x)",
      "Find each deviation x − μ and square it",
      "Multiply each squared deviation by P(x) and add them up to get σ²",
      "Take the square root to get σ",
    ], "The variance is the probability-weighted average squared deviation from the mean."),
  ]);

const l3 = lesson("u4.3", "4.3", "The binomial distribution",
  "The binomial distribution counts successes in a fixed number of independent trials, each with the same probability of success. It is the workhorse of discrete probability.",
  ["Conditions: fixed n trials; each trial success/failure; independent trials; constant p.",
   "Binomial probability distribution X ~ B(n, p): P(X = x) = C(n, x) pˣ qⁿ⁻ˣ where q = 1 − p.",
   "Mean μ = np; standard deviation σ = √(npq).",
   "Calculator: binompdf(n, p, x) for exact; binomcdf(n, p, x) for P(X ≤ x).",
   "P(X ≥ x) = 1 − P(X ≤ x − 1)."],
  [
    G.binomialProbability, G.binomialProbability, G.binomialMeanSD,
    mc(p, "Which situation is binomial?",
      ["Flipping a fair coin 20 times and counting heads", "Drawing 5 cards without replacement and counting aces", "Rolling a die until the first 6 appears", "Measuring the heights of 20 students"],
      "The coin flips satisfy all four conditions. Drawing without replacement changes p; waiting for the first success has no fixed n; heights are continuous."),
    mc(p, "In X ~ B(12, 0.3), what does 12 represent?",
      ["The number of trials", "The number of successes", "The probability of success", "The mean"],
      "B(n, p): the first parameter is the fixed number of trials n; p = 0.3 is the success probability on each trial."),
    num(p, "A basketball player makes 70% of free throws. In 10 attempts, what is the expected number made?", 7,
      "μ = np = 10 × 0.7 = 7.", { tolerance: 0.01 }),
    num(p, "For the same player (n = 10, p = 0.7), what is the standard deviation of the number made? (2 decimals.)", 1.45,
      "σ = √(npq) = √(10 × 0.7 × 0.3) = √2.1 ≈ 1.45.", { tolerance: 0.01 }),
    num(p, "X ~ B(4, 0.5). Find P(X = 2). (4 decimals.)", 0.375,
      "C(4,2)(0.5)²(0.5)² = 6 × 0.0625 = 0.375.", { tolerance: 0.001 }),
    mc(p, "To find P(X ≥ 3) for a binomial variable on a calculator, you should compute…",
      ["1 − binomcdf(n, p, 2)", "binomcdf(n, p, 3)", "binompdf(n, p, 3)", "1 − binomcdf(n, p, 3)"],
      "P(X ≥ 3) is the complement of P(X ≤ 2), and binomcdf(n, p, 2) gives P(X ≤ 2)."),
    tf(p, "In a binomial experiment, the probability of success may change from trial to trial.", false,
      "Constant p across trials is one of the binomial conditions (along with a fixed n, independence, and two outcomes per trial)."),
    mc(p, "The notation X ~ B(n, p) reads as…",
      ["X follows a binomial distribution with n trials and success probability p", "X is between n and p", "X is a bar graph", "X is the number of successes divided by p"],
      "The tilde means 'is distributed as'."),
    match(p, "Match the binomial quantity to its formula.", [
      ["Mean", "np"],
      ["Variance", "npq"],
      ["Standard deviation", "√(npq)"],
      ["P(X = x)", "C(n,x) pˣ qⁿ⁻ˣ"],
    ], "These four formulas cover most binomial problems."),
    mc(p, "A single trial with exactly two possible outcomes (success or failure) and a fixed probability of success is called a…",
      ["Bernoulli trial", "Poisson event", "Geometric step", "Normal draw"],
      "A binomial experiment is a fixed number n of independent Bernoulli trials with the same probability of success p on each trial."),
  ]);

const l4 = lesson("u4.4", "4.4", "The geometric distribution",
  "The geometric distribution models the number of independent trials needed to get the first success. There is no fixed number of trials, only a stopping rule.",
  ["X = trial number of the first success; x = 1, 2, 3, … with no upper limit.",
   "P(X = x) = q^(x−1) p, where q = 1 − p.",
   "Mean μ = 1/p; variance σ² = (1 − p)/p².",
   "Calculator: geometpdf(p, x), geometcdf(p, x)."],
  [
    G.geometricProbability, G.geometricProbability,
    mc(p, "Which scenario is geometric?",
      ["Rolling a die repeatedly and counting how many rolls until the first 6", "Rolling a die 10 times and counting sixes", "Rolling a die once and recording the number", "Measuring how long a die roll takes"],
      "Geometric = repeat independent trials until the first success; the variable is the number of trials needed."),
    num(p, "A job applicant is offered a position at 20% of interviews, independently. What is the expected number of interviews until the first offer?", 5,
      "μ = 1/p = 1/0.2 = 5.", { tolerance: 0.01 }),
    num(p, "With p = 0.2, what is the probability the first offer comes on the third interview? (3 decimals.)", 0.128,
      "P(X = 3) = (0.8)²(0.2) = 0.64 × 0.2 = 0.128.", { tolerance: 0.001 }),
    num(p, "With p = 0.2, what is the probability the first offer takes more than 2 interviews? (2 decimals.)", 0.64,
      "P(X > 2) = P(fail twice) = (0.8)² = 0.64.", { tolerance: 0.006 }),
    mc(p, "What is the largest value a geometric random variable can take?",
      ["There is no upper limit", "n", "1/p", "100"],
      "In theory you could fail forever, so x = 1, 2, 3, … without bound (though large values have tiny probability)."),
    tf(p, "For a geometric distribution, P(X = 1) = p.", true,
      "Success on the very first trial has probability p."),
    mc(p, "How does the geometric distribution differ from the binomial?",
      ["The binomial fixes the number of trials; the geometric counts trials until the first success", "The geometric requires p = 0.5", "The binomial allows dependent trials", "There is no difference"],
      "Both use independent success/failure trials with constant p, but the binomial counts successes in n trials while the geometric counts trials to the first success."),
    mc(p, "As p increases, the expected number of trials until the first success…",
      ["decreases", "increases", "stays the same", "becomes negative"],
      "μ = 1/p, so a higher chance of success means fewer expected trials."),
  ]);

const l5 = lesson("u4.5", "4.5", "The hypergeometric distribution",
  "When you sample without replacement from two groups, trials are not independent and the binomial does not apply. The hypergeometric distribution handles this exactly.",
  ["Population of size N with r 'successes' (group of interest) and N − r 'failures'.",
   "Draw n without replacement; X = number from the group of interest.",
   "Hypergeometric probability: P(X = x) = C(r, x)·C(N − r, n − x) / C(N, n).",
   "Mean μ = n·r/N.",
   "Use hypergeometric instead of binomial when the sample is a large fraction of the population."],
  [
    G.hypergeometric, G.hypergeometric,
    mc(p, "Which situation calls for the hypergeometric distribution?",
      ["Choosing 5 people from a committee of 8 women and 6 men and counting the women", "Flipping a coin 5 times and counting heads", "Waiting for the first defective bulb", "Counting calls to a help line in an hour"],
      "Choosing from a finite set of two groups without replacement is exactly the hypergeometric setup."),
    num(p, "A box holds 6 good and 4 defective parts. Three are drawn without replacement. What is the expected number of defective parts? (1 decimal.)", 1.2,
      "μ = n·r/N = 3 × 4/10 = 1.2.", { tolerance: 0.01 }),
    num(p, "Same box (6 good, 4 defective), 3 drawn. Find P(exactly 1 defective). (4 decimals.)", 0.5,
      "C(4,1)·C(6,2)/C(10,3) = 4 × 15/120 = 60/120 = 0.5.", { tolerance: 0.001 }),
    mc(p, "Why is a hypergeometric experiment NOT binomial?",
      ["Draws without replacement change the probability of success from draw to draw", "The number of trials is not fixed", "There are more than two outcomes", "The probabilities exceed 1"],
      "Without replacement, each draw depends on earlier ones, violating the binomial conditions of independence and constant p."),
    tf(p, "If the population is very large compared with the sample, the binomial distribution closely approximates the hypergeometric.", true,
      "Removing a few items barely changes the proportions, so the draws are nearly independent."),
    mc(p, "In the hypergeometric formula C(r,x)·C(N−r,n−x)/C(N,n), what does C(N, n) count?",
      ["All possible samples of size n from the population", "The number of successes", "The number of failures", "The number of trials"],
      "The denominator counts every equally likely sample; the numerator counts the ones with exactly x from the group of interest."),
  ]);

const l6 = lesson("u4.6", "4.6", "The Poisson distribution",
  "The Poisson distribution counts events in a fixed interval of time or space when events occur independently at a constant average rate: calls per hour, typos per page, cars per minute.",
  ["X ~ P(μ), where μ is the average number of events in the interval.",
   "Poisson probability distribution: P(X = x) = e^(−μ) μˣ / x!, for x = 0, 1, 2, …",
   "Mean = μ and variance = μ (so σ = √μ).",
   "Scale μ to the interval asked about: 3 per hour means 1.5 per half hour.",
   "Poisson approximates binomial when n is large and p is small (μ = np)."],
  [
    G.poissonProbability, G.poissonProbability,
    mc(p, "Which situation is best modeled by a Poisson distribution?",
      ["The number of typos on a page of a book", "The number of heads in 10 coin flips", "The number of rolls until the first 6", "The height of a random student"],
      "Typos occur randomly and independently across the page at some average rate, which is the Poisson setting."),
    num(p, "A call center averages 4 calls per hour. What is the average number of calls in 15 minutes?", 1,
      "Scale the rate to the interval: 4 per hour × (1/4 hour) = 1.", { tolerance: 0.01 }),
    num(p, "Calls average 4 per hour. Find P(exactly 2 calls in an hour). (4 decimals.)", 0.1465,
      "P(X = 2) = e^(−4)·4²/2! = 0.0183 × 16/2 = 0.1465.", { tolerance: 0.001 }),
    num(p, "Calls average 4 per hour. Find P(no calls in an hour). (4 decimals.)", 0.0183,
      "P(X = 0) = e^(−4) = 0.0183.", { tolerance: 0.001 }),
    mc(p, "For a Poisson variable with μ = 9, the standard deviation is…",
      ["3", "9", "81", "4.5"],
      "For Poisson, variance = μ, so σ = √9 = 3."),
    tf(p, "A Poisson random variable can take any non-negative integer value, no matter how large.", true,
      "Like the geometric, it has no upper bound; large counts just have tiny probabilities."),
    mc(p, "A binomial with n = 1,000 and p = 0.002 can be approximated by a Poisson with μ equal to…",
      ["2", "0.002", "1000", "500"],
      "Use μ = np = 1,000 × 0.002 = 2. The approximation works well because n is large and p is small."),
    match(p, "Match each distribution to what its random variable counts.", [
      ["Binomial", "Successes in a fixed number of trials"],
      ["Geometric", "Trials until the first success"],
      ["Hypergeometric", "Successes when sampling without replacement"],
      ["Poisson", "Events in a fixed interval of time or space"],
    ], "Identifying the right distribution is the first step of every discrete probability problem."),
  ]);

export const unit4 = unit(4, "Discrete Random Variables", "Probability distributions, expected value, and the binomial, geometric, hypergeometric, and Poisson models.", "🎯", "#ce82ff", [l1, l2, l3, l4, l5, l6]);
