import { mc, tf, num, match, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u5";

const l1 = lesson("u5.1", "5.1", "Continuous probability functions",
  "A continuous random variable can take any value in an interval, so probability is area under a curve (the probability density function) rather than height at a point.",
  ["f(x) ≥ 0 is the density; the total area under f(x) equals 1.",
   "P(a < X < b) = area under f(x) between a and b.",
   "P(X = c) = 0 for any single value c, so P(X ≤ c) = P(X < c).",
   "The cumulative distribution function F(x) = P(X ≤ x)."],
  [
    G.uniformProbability,
    mc(p, "For a continuous random variable, P(X = 3.5) equals…",
      ["0", "f(3.5)", "0.5", "It depends on the distribution"],
      "A single point has zero width and therefore zero area under the density curve."),
    mc(p, "Which is the correct interpretation of the area under a probability density function between a and b?",
      ["P(a < X < b)", "The mean of X", "f(b) − f(a)", "The number of observations between a and b"],
      "For continuous variables, probability IS area."),
    num(p, "A density function is a rectangle of height 0.25 from x = 0 to x = 4. What is P(1 < X < 3)?", 0.5,
      "Area = width × height = (3 − 1) × 0.25 = 0.5.", { tolerance: 0.001 }),
    tf(p, "For a continuous distribution, P(X < 5) and P(X ≤ 5) are equal.", true,
      "They differ only by P(X = 5), which is 0."),
    mc(p, "The total area under any probability density function is…",
      ["1", "0", "the mean", "unknown until the data are collected"],
      "The total probability of all outcomes is 1."),
    mc(p, "Which statement about a density function f(x) is FALSE?",
      ["f(x) gives the probability that X equals x", "f(x) ≥ 0 for all x", "The area under f(x) is 1", "Probabilities are areas under f(x)"],
      "f(x) is a density, not a probability. Its values can even exceed 1 on narrow intervals."),
    mc(p, "The cumulative distribution function F(x) gives…",
      ["P(X ≤ x)", "P(X = x)", "P(X > x)", "The density at x"],
      "F accumulates probability from the far left up to x."),
    num(p, "If F(2) = 0.3 and F(5) = 0.8 for a continuous variable, what is P(2 < X < 5)?", 0.5,
      "P(2 < X < 5) = F(5) − F(2) = 0.8 − 0.3 = 0.5.", { tolerance: 0.001 }),
  ]);

const l2 = lesson("u5.2", "5.2", "The uniform distribution",
  "The uniform distribution spreads probability evenly over an interval [a, b]: every sub-interval of the same width has the same probability. It is the simplest continuous model.",
  ["X ~ U(a, b); density f(x) = 1/(b − a) for a ≤ x ≤ b.",
   "P(c < X < d) = (d − c)/(b − a).",
   "Mean μ = (a + b)/2; standard deviation σ = (b − a)/√12.",
   "Conditional probabilities use the reduced interval as the new base."],
  [
    G.uniformProbability, G.uniformProbability, G.uniformProbability,
    num(p, "A bus arrives uniformly between 0 and 20 minutes after you reach the stop. Find P(wait less than 5 minutes). (2 decimals.)", 0.25,
      "(5 − 0)/(20 − 0) = 0.25.", { tolerance: 0.006 }),
    num(p, "Same bus (U(0, 20)). What is the mean waiting time?", 10,
      "μ = (0 + 20)/2 = 10 minutes.", { tolerance: 0.01 }),
    num(p, "Same bus (U(0, 20)). Given that you have already waited 8 minutes, what is the probability you wait at least 12 minutes in total? (2 decimals.)", 0.67,
      "Condition on X > 8: the new interval is (8, 20) of length 12. P(X ≥ 12 | X > 8) = (20 − 12)/12 = 0.667.", { tolerance: 0.01 }),
    num(p, "X ~ U(2, 10). What is the height of the density function?", 0.125,
      "f(x) = 1/(b − a) = 1/8 = 0.125.", { tolerance: 0.001 }),
    num(p, "X ~ U(2, 10). Find the 90th percentile.", 9.2,
      "k with (k − 2)/8 = 0.9 gives k = 2 + 7.2 = 9.2.", { tolerance: 0.01 }),
    mc(p, "The graph of a uniform density is…",
      ["a horizontal line segment (rectangle) over the interval", "a bell curve", "a triangle", "a decreasing curve"],
      "Constant density means a flat top; probability of any sub-interval is proportional to its width."),
    tf(p, "For X ~ U(0, 10), P(3 < X < 5) equals P(7 < X < 9).", true,
      "Both intervals have width 2, and a uniform distribution assigns equal probability to equal widths."),
  ]);

const l3 = lesson("u5.3", "5.3", "The exponential distribution",
  "The exponential distribution models waiting times between random events: how long until the next customer, the next earthquake, or a part fails. Small values are most likely and the tail decays exponentially.",
  ["X ~ Exp(m), where m is the decay rate; mean μ = 1/m and σ = 1/m.",
   "P(X < x) = 1 − e^(−mx); P(X > x) = e^(−mx).",
   "Memoryless: P(X > s + t | X > s) = P(X > t).",
   "The exponential (time between events) and Poisson (number of events) describe the same process."],
  [
    G.exponentialProbability, G.exponentialProbability,
    num(p, "A battery's life is exponential with mean 8 years. Find the decay rate m. (3 decimals.)", 0.125,
      "m = 1/μ = 1/8 = 0.125.", { tolerance: 0.001 }),
    num(p, "Battery life ~ Exp with mean 8 years. Find P(lasts more than 10 years). (4 decimals.)", 0.2865,
      "P(X > 10) = e^(−0.125 × 10) = e^(−1.25) = 0.2865.", { tolerance: 0.001 }),
    num(p, "Battery life ~ Exp with mean 8 years. Find P(fails within 2 years). (4 decimals.)", 0.2212,
      "P(X < 2) = 1 − e^(−0.25) = 1 − 0.7788 = 0.2212.", { tolerance: 0.001 }),
    mc(p, "The memoryless property of the exponential distribution says that…",
      ["the probability of surviving another t units does not depend on how long the item has already survived", "the mean equals the median", "the distribution has no mode", "events cannot occur twice"],
      "Given the battery has lasted 5 years, the chance it lasts 3 more is the same as a new battery lasting 3 years."),
    num(p, "Cars arrive at a toll booth at 3 per minute on average (Poisson). What is the mean time between arrivals, in minutes? (3 decimals.)", 0.333,
      "Time between events is exponential with m = 3 per minute, so mean = 1/3 minute.", { tolerance: 0.002 }),
    mc(p, "For an exponential distribution, the standard deviation is…",
      ["equal to the mean", "half the mean", "the square of the mean", "always 1"],
      "Both μ and σ equal 1/m."),
    num(p, "X ~ Exp(0.5). Find the median (the value with P(X < k) = 0.5). (3 decimals.)", 1.386,
      "1 − e^(−0.5k) = 0.5 → e^(−0.5k) = 0.5 → k = ln(2)/0.5 = 1.386.", { tolerance: 0.005 }),
    tf(p, "The exponential density is highest at x = 0 and decreases as x increases.", true,
      "f(x) = m·e^(−mx) starts at m and decays; short waits are most likely."),
    match(p, "Match each quantity for X ~ Exp(m).", [
      ["Mean", "1/m"],
      ["P(X > x)", "e^(−mx)"],
      ["P(X < x)", "1 − e^(−mx)"],
      ["Density f(x)", "m·e^(−mx)"],
    ], "All exponential calculations flow from these four formulas."),
  ]);

export const unit5 = unit(5, "Continuous Random Variables", "Probability as area: density functions, and the uniform and exponential distributions.", "📈", "#ff4b4b", [l1, l2, l3]);
