import { mc, tf, num, match, order, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u7";

const l1 = lesson("u7.1", "7.1", "The central limit theorem for sample means",
  "The central limit theorem (CLT) says that averages of random samples are approximately normally distributed no matter what the population looks like, as long as the sample is large enough. It is the reason the normal distribution is everywhere in inference.",
  ["If samples of size n are drawn from a population with mean μ and SD σ, then X̄ ~ N(μ, σ/√n) approximately.",
   "σ/√n is the standard error of the mean; larger n means less variability in x̄.",
   "n ≥ 30 is a common rule of thumb; if the population is normal, any n works.",
   "z = (x̄ − μ)/(σ/√n) for probabilities about a sample mean."],
  [
    G.cltMeans, G.cltMeans, G.cltMeans,
    mc(p, "What does the central limit theorem say about the distribution of sample means?",
      ["It is approximately normal for large n, regardless of the population's shape", "It matches the population's shape exactly", "It is always uniform", "It is normal only if the population is normal"],
      "The CLT is powerful precisely because it does not require the population to be normal."),
    num(p, "A population has σ = 24. For samples of n = 36, what is the standard deviation of X̄?", 4,
      "σ/√n = 24/6 = 4.", { tolerance: 0.01 }),
    mc(p, "If the sample size is quadrupled, the standard error of the mean is…",
      ["halved", "quartered", "doubled", "unchanged"],
      "Standard error = σ/√n. Multiplying n by 4 multiplies √n by 2, so the SE is cut in half."),
    mc(p, "The mean of the distribution of sample means equals…",
      ["the population mean μ", "μ/√n", "μ·n", "the sample standard deviation"],
      "Sample means are centered at the population mean; only their spread shrinks with n."),
    num(p, "Weights of bags of chips have μ = 200 g, σ = 10 g. For samples of 25 bags, find P(x̄ < 197). (4 decimals.)", 0.0668,
      "SE = 10/5 = 2. z = (197 − 200)/2 = −1.5. P(Z < −1.5) = 0.0668.", { tolerance: 0.002 }),
    tf(p, "The central limit theorem applies to sample means but requires the population to be normally distributed.", false,
      "That is exactly what the CLT frees us from: with a large enough sample, the population's shape does not matter."),
    mc(p, "Which is more likely: a single person's height exceeding 190 cm, or a sample of 50 people having a MEAN height exceeding 190 cm (population mean 175)?",
      ["A single person, because individual values vary more than sample means", "The sample mean, because larger samples give larger values", "They are equally likely", "Cannot be determined"],
      "Means have much smaller spread (σ/√50), so extreme means are far rarer than extreme individuals."),
  ]);

const l2 = lesson("u7.2", "7.2", "The central limit theorem for sums",
  "Sums of random samples are also approximately normal. Instead of shrinking, the spread of a sum grows with √n, and its mean grows with n.",
  ["ΣX ~ N(nμ, √n·σ) approximately for large n.",
   "z = (Σx − nμ)/(√n·σ).",
   "Use sums when the question is about a total (total weight, total time)."],
  [
    G.cltSums, G.cltSums,
    num(p, "Each passenger's luggage weighs on average 20 kg with SD 5 kg. For 64 passengers, what is the mean of the total luggage weight?", 1280,
      "nμ = 64 × 20 = 1,280 kg.", { tolerance: 0.5 }),
    num(p, "Same luggage (μ = 20, σ = 5, n = 64). What is the standard deviation of the total?", 40,
      "√n·σ = 8 × 5 = 40 kg.", { tolerance: 0.01 }),
    num(p, "Same luggage. Find P(total > 1,340 kg). (4 decimals.)", 0.0668,
      "z = (1,340 − 1,280)/40 = 1.5. P(Z > 1.5) = 0.0668.", { tolerance: 0.002 }),
    mc(p, "As n increases, the standard deviation of the sum ΣX…",
      ["increases in proportion to √n", "decreases in proportion to √n", "stays equal to σ", "equals nσ"],
      "Sums accumulate variability: SD(ΣX) = √n·σ. Means average it away: SD(X̄) = σ/√n."),
    tf(p, "For the sum of n independent observations, the mean is nμ.", true,
      "Expected values add: E(ΣX) = n·μ."),
    mc(p, "Which question would be answered with the CLT for sums?",
      ["What is the probability that 40 randomly chosen boxes together weigh more than 850 kg?", "What is the probability that the average box weighs more than 21 kg?", "What is the probability a single box weighs more than 25 kg?", "What is the median box weight?"],
      "Totals of many observations call for the sum version."),
  ]);

const l3 = lesson("u7.3", "7.3", "Using the central limit theorem",
  "Put the CLT to work: recognize whether a question is about an individual, a sample mean, or a sum; pick the right distribution; and compute probabilities and percentiles. Also learn the law of large numbers and the normal approximation for the binomial.",
  ["Individual: X ~ N(μ, σ). Mean: X̄ ~ N(μ, σ/√n). Sum: ΣX ~ N(nμ, √n·σ).",
   "Law of large numbers: x̄ gets closer to μ as n increases.",
   "Percentiles for means: invNorm(area, μ, σ/√n).",
   "Binomial with np > 5 and nq > 5 is approximately N(np, √(npq))."],
  [
    G.cltMeans, G.cltSums,
    mc(p, "Individual runners' times have μ = 40 min and σ = 8 min. Which distribution answers 'What is the probability the average time of 16 runners is under 38 minutes?'",
      ["N(40, 2)", "N(40, 8)", "N(640, 32)", "N(38, 8)"],
      "Sample mean: N(μ, σ/√n) = N(40, 8/4) = N(40, 2)."),
    num(p, "Runners' times: μ = 40, σ = 8. Find P(average of 16 runners < 38). (4 decimals.)", 0.1587,
      "SE = 2; z = (38 − 40)/2 = −1. P(Z < −1) = 0.1587.", { tolerance: 0.002 }),
    num(p, "Runners' times: μ = 40, σ = 8, n = 16. Find the 95th percentile of the sample mean. (2 decimals.)", 43.29,
      "invNorm(0.95) = 1.645. x̄ = 40 + 1.645 × 2 = 43.29.", { tolerance: 0.05 }),
    mc(p, "The law of large numbers implies that…",
      ["the sample mean from a larger sample is likely to be closer to μ", "the sample mean always equals μ when n > 30", "the population becomes normal as n grows", "a run of high values will be followed by low values"],
      "Larger samples average out randomness, so x̄ tends to μ. It says nothing about 'balancing' past outcomes."),
    mc(p, "X ~ B(100, 0.4). Because np = 40 and nq = 60 are both > 5, X is approximately…",
      ["N(40, √24 ≈ 4.9)", "N(40, 24)", "N(0.4, 0.049)", "N(100, 40)"],
      "Mean np = 40; SD = √(npq) = √(100 × 0.4 × 0.6) = √24 ≈ 4.9."),
    tf(p, "When a question asks about a total of many observations, you should use the distribution of the sum, N(nμ, √n·σ).", true,
      "Match the distribution to what the question is about: individual, mean, or sum."),
    order(p, "Order the steps for a CLT probability problem about a sample mean.", [
      "Identify μ, σ, and n",
      "Write the distribution of X̄ as N(μ, σ/√n)",
      "Convert the question into a z-score or calculator command",
      "Find the area and interpret it as a probability",
    ], "Sketching the curve and shading the region helps at step 3."),
    match(p, "Match each quantity to its sampling distribution.", [
      ["Single observation X", "N(μ, σ)"],
      ["Sample mean X̄", "N(μ, σ/√n)"],
      ["Sample sum ΣX", "N(nμ, √n·σ)"],
      ["Binomial count (large n)", "N(np, √(npq))"],
    ], "Choosing the right distribution is most of the work in CLT problems."),
  ]);

export const unit7 = unit(7, "The Central Limit Theorem", "Why sample means and sums are normal, and how to use that to compute probabilities.", "🧲", "#00cd9c", [l1, l2, l3]);
