import { mc, tf, num, match, order, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u8";

const l1 = lesson("u8.1", "8.1", "Confidence interval for a mean, σ known",
  "A confidence interval turns a point estimate into a range that probably contains the population parameter. When σ is known, the interval for μ uses the normal distribution.",
  ["CI = x̄ ± EBM, where the error bound for a population mean (EBM) = z_(α/2)·σ/√n.",
   "A point estimate (x̄) is a single number; a confidence interval is an interval estimate. Confidence level CL = 1 − α, so α = 1 − CL is split between the two tails.",
   "Working backwards: EBM = (upper − lower)/2 and x̄ = (upper + lower)/2.",
   "z for 90%: 1.645; 95%: 1.96; 99%: 2.576.",
   "Interpretation: we are CL% confident the interval contains μ. It is NOT the probability μ is inside this particular interval.",
   "Wider with higher confidence or larger σ; narrower with larger n. Required n = (zσ/EBM)²."],
  [
    G.ciMeanKnownSigma, G.ciMeanKnownSigma, G.sampleSizeForMean,
    num(p, "A sample of 49 light bulbs has x̄ = 1,200 hours; σ = 70 hours is known. Find the error bound for a 95% confidence interval. (2 decimals.)", 19.6,
      "EBM = 1.96 × 70/√49 = 1.96 × 10 = 19.6.", { tolerance: 0.05 }),
    mc(p, "Using x̄ = 1,200 and EBM = 19.6, the 95% confidence interval for μ is…",
      ["(1180.4, 1219.6)", "(1200, 1219.6)", "(1190.2, 1209.8)", "(1130, 1270)"],
      "x̄ ± EBM = 1,200 ± 19.6."),
    mc(p, "Which is the correct interpretation of a 95% confidence interval (1180.4, 1219.6) for the mean bulb life?",
      ["We are 95% confident that the true mean bulb life is between 1180.4 and 1219.6 hours", "95% of bulbs last between 1180.4 and 1219.6 hours", "There is a 95% chance that x̄ is between 1180.4 and 1219.6", "95% of samples will have a mean in this interval"],
      "The confidence is about the procedure capturing the population mean μ, not about individual bulbs or the sample mean (which is certainly inside)."),
    mc(p, "What happens to the width of a confidence interval if the confidence level is raised from 90% to 99% (everything else fixed)?",
      ["It gets wider", "It gets narrower", "It stays the same", "It becomes zero"],
      "More confidence requires a larger z (1.645 → 2.576), so a larger error bound."),
    mc(p, "What happens to the width of a confidence interval if the sample size is increased from 25 to 100?",
      ["It is cut in half", "It doubles", "It is cut to a quarter", "It stays the same"],
      "EBM ∝ 1/√n; √100/√25 = 2, so the error bound halves."),
    tf(p, "'95% confidence' means that if we repeated the sampling many times, about 95% of the intervals produced would contain μ.", true,
      "This long-run interpretation is what the confidence level actually describes."),
    num(p, "A 90% confidence interval for μ is (54, 62). What was the sample mean?", 58,
      "x̄ is the midpoint: (54 + 62)/2 = 58. The error bound is 4.", { tolerance: 0.01 }),
    num(p, "How large a sample is needed to estimate μ within 2 units with 95% confidence if σ = 12? (Round up.)", 139,
      "n = (zσ/EBM)² = (1.96 × 12/2)² = (11.76)² = 138.3 → 139.", { tolerance: 0 }),
    match(p, "Match each confidence level to its z critical value.", [
      ["90%", "1.645"],
      ["95%", "1.96"],
      ["99%", "2.576"],
      ["80%", "1.28"],
    ], "These values are the z-scores leaving α/2 in each tail."),
    G.ciBackwards, G.ciBackwards,
    mc(p, "A sample mean of 42.6 is reported as the estimate of a population mean. This single number is a…",
      ["point estimate", "confidence interval", "confidence level", "parameter"],
      "A point estimate is one number computed from a sample to estimate a parameter. A confidence interval surrounds it with an error bound."),
    num(p, "For a 90% confidence interval, what is α? (2 decimals.)", 0.1,
      "α = 1 − CL = 1 − 0.90 = 0.10. Half of it (0.05) goes in each tail, which is why z_(α/2) = 1.645.", { tolerance: 0.001 }),
    mc(p, "What does a confidence level of 90% mean?",
      ["If we took many samples and built an interval from each, about 90 out of 100 intervals would contain the true parameter", "There is a 90% chance the sample mean is correct", "90% of the population lies inside the interval", "The interval contains 90% of the sample data"],
      "The confidence level describes the long-run success rate of the interval-building procedure, not a probability about one particular interval."),
  ]);

const l2 = lesson("u8.2", "8.2", "Confidence interval for a mean, σ unknown (Student's t)",
  "In practice σ is rarely known. Using the sample standard deviation s adds uncertainty, so we replace z with the Student's t distribution, which has heavier tails and depends on degrees of freedom.",
  ["Student's t-distribution: EBM = t_(α/2)·s/√n with df = n − 1; CI = x̄ ± EBM.",
   "t is wider than z, especially for small n; as df grows, t approaches z.",
   "Requires a roughly normal population or a large sample.",
   "Calculator: invT(area to the left, df) or TInterval."],
  [
    G.ciMeanT, G.ciMeanT, G.ciMeanT,
    mc(p, "When should you use the t distribution rather than z for a confidence interval for μ?",
      ["When the population standard deviation is unknown and estimated by s", "When the sample size is over 100", "When the data are categorical", "When the confidence level is 99%"],
      "The extra uncertainty from estimating σ is what t accounts for."),
    num(p, "A sample of n = 16 has x̄ = 50 and s = 8. For 95% confidence, t_(α/2) with df = 15 is 2.131. Find the error bound. (2 decimals.)", 4.26,
      "EBM = 2.131 × 8/√16 = 2.131 × 2 = 4.26.", { tolerance: 0.02 }),
    mc(p, "Using x̄ = 50 and EBM = 4.26, the 95% interval is…",
      ["(45.74, 54.26)", "(50, 54.26)", "(42, 58)", "(41.48, 58.52)"],
      "The interval is x̄ ± EBM = 50 ± 4.26, giving (45.74, 54.26)."),
    mc(p, "Compared with the standard normal, the t distribution…",
      ["has heavier tails and more spread, especially for small df", "is skewed to the right", "has a smaller standard deviation", "is identical for all sample sizes"],
      "Heavier tails reflect the extra uncertainty of estimating σ; with large df the two curves are nearly the same."),
    num(p, "What are the degrees of freedom for a t confidence interval based on a sample of 23 observations?", 22,
      "df = n − 1 = 22.", { tolerance: 0 }),
    tf(p, "As the degrees of freedom increase, the t critical value gets closer to the z critical value.", true,
      "For example, t with 5 df at 95% is 2.571; with 100 df it is 1.984; z is 1.960."),
    mc(p, "A researcher computes a 95% t interval from n = 10 and gets (12, 28). A colleague uses z = 1.96 by mistake with the same data. The colleague's interval will be…",
      ["narrower than (12, 28)", "wider than (12, 28)", "the same", "centered at a different value"],
      "t_(9) = 2.262 > 1.96, so the correct t interval is wider; using z understates the uncertainty."),
    mc(p, "Degrees of freedom for a t confidence interval are defined as…",
      ["the number of values in the sample that are free to vary, n − 1", "the sample size n", "the number of population parameters", "n − 2"],
      "Once the sample mean is fixed, only n − 1 of the deviations can vary freely; that is why df = n − 1 for a single sample."),
    mc(p, "Which of these is NOT a property of the Student's t-distribution?",
      ["It is skewed to the right", "It is symmetric about a mean of zero", "It is more spread out than the standard normal", "It approaches the standard normal as the degrees of freedom increase"],
      "The t-distribution is symmetric and bell-shaped but flatter and heavier-tailed than the normal; each df defines a different member of the family."),
  ]);

const l3 = lesson("u8.3", "8.3", "Confidence interval for a proportion",
  "To estimate a population proportion p (the fraction with some characteristic), use the sample proportion p′ = x/n and the normal approximation.",
  ["p′ = x/n, q′ = 1 − p′. EBP = z_(α/2)·√(p′q′/n).",
   "CI = p′ ± EBP. Requires np′ > 5 and nq′ > 5.",
   "Sample size for a proportion: n = z²p′q′/EBP²; with no estimate, use p′ = 0.5 (most conservative).",
   "The 'plus four' interval adds 2 successes and 2 failures for small samples."],
  [
    G.ciProportion, G.ciProportion,
    num(p, "In a survey of 400 adults, 140 prefer online shopping. Find p′. (2 decimals.)", 0.35,
      "p′ = 140/400 = 0.35.", { tolerance: 0.005 }),
    num(p, "Using p′ = 0.35 and n = 400, find the error bound for a 95% confidence interval. (3 decimals.)", 0.047,
      "EBP = 1.96 × √(0.35 × 0.65/400) = 1.96 × 0.02385 = 0.0467.", { tolerance: 0.002 }),
    mc(p, "Using p′ = 0.35 and EBP ≈ 0.047, the 95% confidence interval is…",
      ["(0.303, 0.397)", "(0.35, 0.397)", "(0.30, 0.40)", "(0.256, 0.444)"],
      "p′ ± EBP = 0.35 ± 0.047."),
    num(p, "A pollster wants to estimate a proportion within 3 percentage points with 95% confidence and has no prior estimate. What sample size is needed? (Round up.)", 1068,
      "n = z²(0.5)(0.5)/0.03² = 3.8416 × 0.25/0.0009 = 1067.1 → 1,068.", { tolerance: 0 }),
    mc(p, "Why is p′ = 0.5 used when no prior estimate of a proportion is available?",
      ["It maximizes p′q′ and therefore gives the largest (safest) sample size", "It is the most common proportion in surveys", "It makes the interval narrowest", "It is required by the normal distribution"],
      "p′q′ is largest at p′ = 0.5, so the resulting n is large enough for any true proportion."),
    mc(p, "A 95% confidence interval for the proportion of defective parts is (0.02, 0.06). Which statement is correct?",
      ["We are 95% confident the true defect proportion is between 2% and 6%", "95% of parts are defective", "The sample proportion is 6%", "There is a 95% chance the next part is defective"],
      "The interval estimates the population proportion, not the outcome of an individual part."),
    tf(p, "The confidence interval for a proportion is centered at the sample proportion p′.", true,
      "The interval is p′ ± EBP, so p′ sits exactly in the middle."),
    order(p, "Order the steps for building a confidence interval for a proportion.", [
      "Compute p′ = x/n and q′ = 1 − p′",
      "Check np′ > 5 and nq′ > 5",
      "Find z for the confidence level",
      "Compute EBP = z·√(p′q′/n)",
      "Report p′ ± EBP and interpret",
    ], "Checking the conditions ensures the normal approximation is reasonable."),
    num(p, "A small survey finds 6 successes in 20 trials. Using the plus-four method, what is the adjusted sample proportion p′? (2 decimals.)", 0.33,
      "Add two successes and two failures: p′ = (6 + 2)/(20 + 4) = 8/24 = 0.33. For small samples this adjustment gives more accurate intervals.", { tolerance: 0.006 }),
    mc(p, "The plus-four method for a proportion interval…",
      ["adds two imaginary successes and two imaginary failures before computing p′ and the interval", "adds four to the sample size only", "multiplies the error bound by four", "is used only when n > 1,000"],
      "The adjustment pulls p′ slightly toward 0.5 and is recommended when the sample is small."),
    num(p, "You want to estimate a proportion within 0.04 with 90% confidence and a prior estimate p′ = 0.30. What sample size is needed? (Round up.)", 356,
      "n = z²p′q′/EBP² = (1.645)²(0.30)(0.70)/0.04² = 2.706 × 0.21/0.0016 = 355.1 → 356.", { tolerance: 0 }),
  ]);

export const unit8 = unit(8, "Confidence Intervals", "Estimate a mean or proportion with a range and a confidence level.", "🎯", "#ffc800", [l1, l2, l3]);
