import { mc, tf, num, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u9";

const l1 = lesson("u9.1", "9.1", "Null and alternative hypotheses",
  "A hypothesis test starts with two competing statements about a population parameter. The null hypothesis H₀ is the claim we assume true until the data say otherwise; the alternative Hₐ is what we are looking for evidence of.",
  ["H₀ always contains equality: =, ≤, or ≥ (the book writes = in H₀).",
   "Hₐ uses <, >, or ≠ and never contains equality.",
   "Hypotheses are about parameters (μ, p), never about statistics (x̄, p′).",
   "Left-tailed (<), right-tailed (>), or two-tailed (≠) depending on Hₐ."],
  [
    G.hypothesisSetup, G.hypothesisSetup, G.hypothesisSetup,
    mc(p, "Which symbol can NEVER appear in an alternative hypothesis?",
      ["=", "<", ">", "≠"],
      "The alternative is what the data would have to show; it never contains equality."),
    mc(p, "A company claims its batteries last 500 hours on average. A consumer group thinks they last less. The null hypothesis is…",
      ["H₀: μ = 500", "H₀: μ < 500", "H₀: x̄ = 500", "H₀: μ ≠ 500"],
      "The null states the claim/status quo with equality about the population mean μ."),
    tf(p, "The hypotheses H₀: x̄ = 50 and Hₐ: x̄ > 50 are correctly written.", false,
      "Hypotheses are statements about population parameters; x̄ is a sample statistic we already know. Write μ instead."),
    classify(p, "Classify each alternative hypothesis by its tail.", ["Left-tailed", "Right-tailed", "Two-tailed"], [
      ["Hₐ: μ < 20", "Left-tailed"],
      ["Hₐ: p > 0.4", "Right-tailed"],
      ["Hₐ: μ ≠ 100", "Two-tailed"],
      ["Hₐ: p < 0.5", "Left-tailed"],
    ], "The direction of the inequality in Hₐ names the tail where evidence against H₀ would appear."),
    mc(p, "A researcher wants to show that a new teaching method changes the mean test score, in either direction. The alternative hypothesis is…",
      ["Hₐ: μ ≠ 75", "Hₐ: μ > 75", "Hₐ: μ < 75", "Hₐ: μ = 75"],
      "'Changes' with no direction stated calls for a two-tailed alternative."),
    mc(p, "The null hypothesis is best described as…",
      ["the statement assumed true unless the data provide strong evidence against it", "the researcher's belief", "the statement that is always rejected", "a statement about the sample"],
      "The burden of proof is on the alternative; H₀ gets the benefit of the doubt."),
  ]);

const l2 = lesson("u9.2", "9.2", "Type I and Type II errors",
  "Because decisions are based on samples, they can be wrong in two ways. Understanding both errors and their probabilities (α and β) is essential for interpreting any test.",
  ["Type I error: rejecting H₀ when it is true. P(Type I) = α, the significance level.",
   "Type II error: failing to reject H₀ when it is false. P(Type II) = β.",
   "Power = 1 − β: the probability of correctly rejecting a false H₀.",
   "Lowering α raises β for a fixed n; increasing n lowers both."],
  [
    G.errorTypes, G.errorTypes,
    mc(p, "A test uses α = 0.05. What does this mean?",
      ["There is a 5% chance of rejecting a true null hypothesis", "There is a 5% chance the null hypothesis is true", "5% of the data are outliers", "The test has 95% power"],
      "α is the probability of a Type I error, set by the researcher before seeing the data."),
    mc(p, "A smoke detector's null hypothesis is 'there is no fire.' A Type II error would be…",
      ["Failing to sound the alarm when there is a fire", "Sounding the alarm when there is no fire", "Sounding the alarm during a fire", "Staying silent when there is no fire"],
      "Type II = failing to reject a false null: there IS a fire (H₀ false) and the detector stays silent."),
    mc(p, "For the smoke detector, which error is more serious?",
      ["Type II (missing a real fire)", "Type I (a false alarm)", "They are equally serious", "Neither is serious"],
      "Consequences decide which error matters more; here a missed fire could be deadly, so designers accept more false alarms."),
    match(p, "Match each term to its definition.", [
      ["Type I error", "Reject a true H₀"],
      ["Type II error", "Fail to reject a false H₀"],
      ["α", "Probability of a Type I error"],
      ["Power", "1 − β"],
    ], "These four ideas describe everything that can go right or wrong in a decision."),
    tf(p, "Decreasing α (with the same sample size) makes a Type II error more likely.", true,
      "Being stricter about rejecting H₀ means more real effects go undetected: α and β trade off unless n increases."),
    mc(p, "Which action reduces both α and β at the same time?",
      ["Increasing the sample size", "Lowering the significance level", "Raising the significance level", "Using a one-tailed test"],
      "More data sharpens the test; with fixed n, reducing one error type increases the other."),
    mc(p, "In a court trial with H₀: the defendant is innocent, the power of the trial is…",
      ["the probability of convicting a guilty defendant", "the probability of convicting an innocent defendant", "the probability of acquitting a guilty defendant", "the probability of a hung jury"],
      "Power = probability of rejecting H₀ (convicting) when H₀ is false (the defendant is guilty)."),
  ]);

const l3 = lesson("u9.3", "9.3", "Distributions used in hypothesis testing",
  "Which distribution the test statistic follows depends on what you are testing and what you know. Means use z (σ known) or t (σ unknown); proportions use z with the null proportion.",
  ["Mean, σ known: X̄ ~ N(μ₀, σ/√n); z = (x̄ − μ₀)/(σ/√n).",
   "Mean, σ unknown: t = (x̄ − μ₀)/(s/√n) with df = n − 1.",
   "Proportion: z = (p′ − p₀)/√(p₀q₀/n); need np₀ > 5 and nq₀ > 5.",
   "Assumptions: random sample; normal population or large n; binomial conditions for proportions."],
  [
    G.zTestStatistic, G.tTestStatistic, G.proportionTest,
    mc(p, "You test a claim about a population mean using a sample of 15 with unknown σ from an approximately normal population. Which distribution do you use?",
      ["Student's t with 14 degrees of freedom", "Standard normal z", "Chi-square with 14 df", "Binomial"],
      "Unknown σ estimated by s means t; df = n − 1 = 14."),
    mc(p, "You test whether the proportion of defective chips exceeds 0.02 using n = 1,000. Which distribution is used?",
      ["Normal, because np₀ = 20 and nq₀ = 980 are both greater than 5", "t with 999 df", "Uniform", "Chi-square"],
      "Proportion tests use the normal approximation to the binomial when both np₀ and nq₀ exceed 5."),
    num(p, "Test H₀: μ = 100 with σ = 15 known, n = 36, x̄ = 106. Find z. (2 decimals.)", 2.4,
      "z = (106 − 100)/(15/√36) = 6/2.5 = 2.4.", { tolerance: 0.02 }),
    num(p, "Test H₀: p = 0.30 with n = 200 and 75 successes. Find z. (2 decimals.)", 2.31,
      "p′ = 0.375. z = (0.375 − 0.30)/√(0.30 × 0.70/200) = 0.075/0.0324 = 2.31.", { tolerance: 0.03 }),
    tf(p, "In a test for a proportion, the standard error uses the null value p₀, not the sample value p′.", true,
      "Under H₀ we assume p = p₀, so the test statistic's denominator uses p₀q₀."),
    mc(p, "Which is NOT an assumption for a t-test of a single mean?",
      ["The population standard deviation is known", "The sample is a simple random sample", "The population is approximately normal or the sample is large", "The data are quantitative"],
      "If σ were known we would use z, not t."),
  ]);

const l4 = lesson("u9.4", "9.4", "Rare events, p-values, and decisions",
  "A p-value is the probability, assuming H₀ is true, of getting a sample at least as extreme as the one observed. A tiny p-value means the data would be a rare event under H₀, so we reject H₀.",
  ["p-value: P(data this extreme or more | H₀ true).",
   "Decision: p-value < α → reject H₀; p-value ≥ α → do not reject H₀.",
   "Never 'accept' H₀: a large p-value means insufficient evidence, not proof.",
   "Conclusion must be stated in context: 'There is (not) sufficient evidence that…'.",
   "Two-tailed p-value = 2 × one-tail area."],
  [
    G.pValueDecision, G.pValueDecision, G.tTestStatistic,
    mc(p, "A p-value of 0.003 means…",
      ["If H₀ were true, a sample this extreme would occur only 0.3% of the time", "There is a 0.3% chance that H₀ is true", "There is a 99.7% chance that Hₐ is true", "The sample is 0.3% of the population"],
      "The p-value is a conditional probability computed assuming H₀; it is not the probability that either hypothesis is true."),
    mc(p, "With α = 0.05 and p-value = 0.08, the correct conclusion is…",
      ["Do not reject H₀; there is not sufficient evidence to support Hₐ", "Reject H₀; the evidence supports Hₐ", "Accept H₀; it has been proven true", "The test is inconclusive and must be redone"],
      "p ≥ α means the data are not unusual enough under H₀. We fail to reject, which is not the same as proving H₀."),
    mc(p, "A right-tailed z-test gives z = 2.05. The p-value is…",
      ["P(Z > 2.05) ≈ 0.020", "P(Z < 2.05) ≈ 0.980", "2 × P(Z > 2.05) ≈ 0.040", "0.05"],
      "Right-tailed means the p-value is the area to the right of the test statistic."),
    mc(p, "A two-tailed test gives z = −2.05. The p-value is…",
      ["2 × P(Z < −2.05) ≈ 0.040", "P(Z < −2.05) ≈ 0.020", "P(Z > −2.05) ≈ 0.980", "0.05"],
      "For a two-tailed test, double the one-tail area to account for extremes in both directions."),
    tf(p, "A p-value of 0.30 proves that the null hypothesis is true.", false,
      "A large p-value only means the data are consistent with H₀. Absence of evidence is not evidence of absence."),
    mc(p, "H₀: μ = 12 oz (fill of soda cans), Hₐ: μ < 12. With α = 0.05 the p-value is 0.01. The conclusion in context is…",
      ["There is sufficient evidence that the mean fill is less than 12 oz", "There is sufficient evidence that the mean fill equals 12 oz", "The mean fill is exactly 12 oz", "There is not sufficient evidence that the mean fill is less than 12 oz"],
      "p < α → reject H₀ and conclude in favor of Hₐ, stated in the language of the problem."),
    order(p, "Order the steps of a hypothesis test.", [
      "State H₀ and Hₐ",
      "Choose α and identify the appropriate distribution",
      "Compute the test statistic and the p-value",
      "Compare the p-value with α and decide",
      "Write the conclusion in context",
    ], "Following the same steps every time keeps tests clear and honest."),
  ]);

const l5 = lesson("u9.5", "9.5", "Full hypothesis tests",
  "Now put every piece together: set up hypotheses, check assumptions, compute the statistic and p-value, decide, and conclude, for means and proportions.",
  ["Mean, σ known → Z-Test; σ unknown → T-Test; proportion → 1-PropZTest.",
   "Sketch the distribution and shade the p-value region.",
   "Decision rule: reject H₀ if p-value < α.",
   "State both the decision and a plain-language conclusion."],
  [
    G.zTestStatistic, G.tTestStatistic, G.proportionTest, G.pValueDecision,
    mc(p, "A coffee shop claims the mean wait is at most 4 minutes. In 36 visits the mean wait was 4.5 minutes with σ = 1.2 known. Test at α = 0.05. The test statistic is z = 2.5 and the p-value ≈ 0.006. Conclusion?",
      ["Reject H₀: there is sufficient evidence the mean wait exceeds 4 minutes", "Do not reject H₀: the wait is at most 4 minutes", "Accept H₀", "The test cannot be done because σ is known"],
      "Hₐ: μ > 4 (right-tailed). p = 0.006 < 0.05, so reject H₀."),
    mc(p, "A candidate claims 55% support. A poll of 500 finds 250 supporters (p′ = 0.50). z = (0.50 − 0.55)/√(0.55·0.45/500) ≈ −2.25, two-tailed p ≈ 0.024. At α = 0.01 the decision is…",
      ["Do not reject H₀ because 0.024 > 0.01", "Reject H₀ because 0.024 < 0.05", "Reject H₀ because z is negative", "Accept Hₐ"],
      "Compare the p-value with the stated α = 0.01, not 0.05. 0.024 > 0.01, so we fail to reject."),
    mc(p, "A t-test with n = 12 gives t = 1.5 for Hₐ: μ ≠ 50. Which calculator command produces the p-value?",
      ["2 × tcdf(1.5, 1E99, 11)", "tcdf(1.5, 1E99, 12)", "normalcdf(1.5, 1E99)", "tcdf(−1E99, 1.5, 11)"],
      "Two-tailed: double the right-tail area; df = n − 1 = 11."),
    num(p, "A t-test with n = 12 gives t = 1.5, two-tailed. Find the p-value. (3 decimals.)", 0.162,
      "2 × P(T₁₁ > 1.5) = 2 × 0.081 = 0.162.", { tolerance: 0.005 }),
    tf(p, "If the p-value is less than α, we reject the null hypothesis and the result is called statistically significant.", true,
      "'Statistically significant' means the observed result would be unlikely if H₀ were true."),
    mc(p, "A test result is statistically significant at α = 0.05 but the estimated effect is tiny. What is the best interpretation?",
      ["The effect is unlikely to be zero, but it may be too small to matter in practice", "The effect must be large", "The test was done incorrectly", "The p-value must be wrong"],
      "Statistical significance is about evidence, not importance; with large n even trivial effects become significant."),
    mc(p, "Which of these is a correctly stated conclusion when H₀ is NOT rejected?",
      ["At the 5% level, there is not sufficient evidence to conclude that the mean differs from 50", "At the 5% level, we have proven the mean is 50", "The alternative hypothesis is false", "The null hypothesis is accepted as true"],
      "Failing to reject is a statement about insufficient evidence, never proof of H₀."),
  ]);

export const unit9 = unit(9, "Hypothesis Testing with One Sample", "Set up hypotheses, understand errors, compute p-values, and draw conclusions.", "⚖️", "#ff86d0", [l1, l2, l3, l4, l5]);
