import { mc, tf, num, match, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u10";

const l1 = lesson("u10.1", "10.1", "Two means with unknown standard deviations",
  "Comparing two independent groups is one of the most common questions in statistics. When σ₁ and σ₂ are unknown, use a two-sample t-test on the difference of sample means.",
  ["H₀: μ₁ − μ₂ = 0 (or μ₁ = μ₂); Hₐ uses <, >, or ≠.",
   "t = (x̄₁ − x̄₂ − 0)/√(s₁²/n₁ + s₂²/n₂).",
   "Degrees of freedom come from the Welch formula (calculator: 2-SampTTest, not pooled).",
   "Requires independent random samples from roughly normal populations or large n.",
   "Effect size: Cohen's d = (x̄₁ − x̄₂)/s_pooled with s_pooled = √(((n₁−1)s₁² + (n₂−1)s₂²)/(n₁+n₂−2)); 0.2 small, 0.5 medium, 0.8 large."],
  [
    G.twoMeansStat, G.twoMeansStat, G.twoMeansStat,
    mc(p, "Which situation calls for a two-sample t-test with independent samples?",
      ["Comparing mean recovery times of patients randomly assigned to two different treatments", "Comparing each patient's blood pressure before and after treatment", "Testing whether one group's mean equals 100", "Comparing proportions of two groups who recover"],
      "Two separate groups of different subjects, quantitative outcome, unknown σ: independent two-sample t."),
    mc(p, "The null hypothesis for comparing two population means is usually written…",
      ["H₀: μ₁ − μ₂ = 0", "H₀: x̄₁ = x̄₂", "H₀: μ₁ − μ₂ ≠ 0", "H₀: s₁ = s₂"],
      "The null says there is no difference between the population means."),
    num(p, "Group A: x̄ = 85, s = 6, n = 20. Group B: x̄ = 80, s = 8, n = 25. Find the standard error √(s₁²/n₁ + s₂²/n₂). (3 decimals.)", 2.088,
      "√(36/20 + 64/25) = √(1.8 + 2.56) = √4.36 = 2.088.", { tolerance: 0.003 }),
    num(p, "Same data (x̄ₐ = 85, x̄ᵦ = 80, SE = 2.088). Find t. (2 decimals.)", 2.39,
      "t = (85 − 80)/2.088 = 2.39.", { tolerance: 0.02 }),
    mc(p, "A two-sample t-test gives t = 2.39 and p-value 0.021 for Hₐ: μₐ ≠ μᵦ. At α = 0.05…",
      ["Reject H₀: there is sufficient evidence the population means differ", "Do not reject H₀", "Accept H₀: the means are equal", "The test is invalid because t > 2"],
      "0.021 < 0.05, so the difference is statistically significant."),
    tf(p, "In a two-sample t-test, the sample sizes must be equal.", false,
      "Unequal sample sizes are fine; the formula uses each n separately."),
    mc(p, "Why is the degrees-of-freedom formula for the two-sample t-test complicated?",
      ["Because the two samples have different variances and sizes, and df is approximated to keep the t distribution accurate", "Because two-sample tests always use df = n − 1", "Because the test uses the normal distribution", "It is not complicated; df = n₁ + n₂"],
      "The Welch–Satterthwaite approximation adjusts df for unequal variances; a calculator computes it automatically."),
    G.cohensD, G.cohensD,
    mc(p, "In a two-sample t-test with unknown standard deviations, the random variable is…",
      ["X̄₁ − X̄₂, the difference of the sample means", "the larger sample mean", "s₁ − s₂", "the pooled proportion"],
      "The test asks whether the observed difference of sample means is unusual if the population means were equal."),
    mc(p, "A two-sample test is statistically significant (p = 0.001) but Cohen's d = 0.1. What is the best interpretation?",
      ["The difference is real but very small in practical terms", "The result must be a mistake", "The effect is large", "The p-value should be recomputed"],
      "Statistical significance answers whether a difference exists; effect size answers how big it is. Large samples can make tiny differences significant."),
  ]);

const l2 = lesson("u10.2", "10.2", "Two means with known standard deviations",
  "When both population standard deviations are known (rare in practice), the difference of sample means follows a normal distribution and the test uses z.",
  ["z = (x̄₁ − x̄₂ − 0)/√(σ₁²/n₁ + σ₂²/n₂).",
   "Same hypotheses and decision rule as the t version.",
   "The standard error uses the known σ values, not sample s values."],
  [
    G.twoMeansKnownSigma, G.twoMeansKnownSigma, G.twoMeansKnownSigma,
    mc(p, "Which distribution is used to compare two means when both population standard deviations are known?",
      ["Standard normal (z)", "Student's t", "Chi-square", "F"],
      "Known σ's mean no extra estimation uncertainty, so z applies."),
    num(p, "Plant A: x̄ = 52, σ = 4, n = 40. Plant B: x̄ = 50, σ = 5, n = 50. Find z for H₀: μₐ − μᵦ = 0. (2 decimals.)", 2.11,
      "SE = √(16/40 + 25/50) = √(0.4 + 0.5) = 0.9487. z = 2/0.9487 = 2.11.", { tolerance: 0.02 }),
    num(p, "With z = 2.11 and Hₐ: μₐ > μᵦ, find the p-value. (4 decimals.)", 0.0174,
      "Right tail: P(Z > 2.11) = 0.0174.", { tolerance: 0.002 }),
    mc(p, "With p-value 0.0174 and α = 0.01, the decision is…",
      ["Do not reject H₀", "Reject H₀", "Accept H₀", "Increase α"],
      "0.0174 > 0.01: not enough evidence at the 1% level (though there would be at 5%)."),
    tf(p, "The z-test for two means uses σ₁ and σ₂ in the standard error, while the t-test uses s₁ and s₂.", true,
      "That is the whole difference between the two procedures."),
    mc(p, "Two independent samples each have n = 100 and both σ = 10. The standard error of x̄₁ − x̄₂ is…",
      ["√(100/100 + 100/100) = 1.41", "10", "0.1", "20"],
      "√(σ₁²/n₁ + σ₂²/n₂) = √(1 + 1) = √2 ≈ 1.41."),
  ]);

const l3 = lesson("u10.3", "10.3", "Comparing two independent proportions",
  "To compare the proportions of two populations, pool the samples under the null hypothesis to estimate the common proportion, then use a z statistic.",
  ["p′₁ = x₁/n₁, p′₂ = x₂/n₂; pooled p_c = (x₁ + x₂)/(n₁ + n₂).",
   "z = (p′₁ − p′₂)/√(p_c(1 − p_c)(1/n₁ + 1/n₂)).",
   "H₀: p₁ = p₂. Need at least 5 successes and 5 failures in each sample.",
   "Calculator: 2-PropZTest."],
  [
    G.twoProportionsStat, G.twoProportionsStat, G.twoProportionsStat,
    num(p, "Drug: 60 of 200 patients improved. Placebo: 40 of 200 improved. Find the pooled proportion p_c. (2 decimals.)", 0.25,
      "(60 + 40)/(200 + 200) = 100/400 = 0.25.", { tolerance: 0.005 }),
    num(p, "Same data (p′₁ = 0.30, p′₂ = 0.20, p_c = 0.25, n₁ = n₂ = 200). Find z. (2 decimals.)", 2.31,
      "SE = √(0.25 × 0.75 × (1/200 + 1/200)) = √0.001875 = 0.0433. z = 0.10/0.0433 = 2.31.", { tolerance: 0.03 }),
    mc(p, "With z = 2.31 for Hₐ: p₁ > p₂, the p-value ≈ 0.010. At α = 0.05…",
      ["Reject H₀: the drug's improvement rate is significantly higher", "Do not reject H₀", "Accept H₀", "The result is not significant because z < 3"],
      "0.010 < 0.05, so there is sufficient evidence that the drug's proportion exceeds the placebo's."),
    mc(p, "Why is a pooled proportion used in the two-proportion z-test?",
      ["Under H₀ the two proportions are equal, so combining the samples gives the best estimate of that common value", "It makes the sample sizes equal", "It reduces the p-value", "Because proportions cannot be compared otherwise"],
      "The test statistic is computed assuming H₀ is true, and pooling uses that assumption."),
    tf(p, "The two-proportion z-test requires that each sample have at least five successes and five failures.", true,
      "This keeps the normal approximation to the binomial reasonable."),
    classify(p, "Which two-sample test fits each scenario?", ["Two means (t)", "Two proportions (z)", "Paired (matched)"], [
      ["Compare the fraction of men and women who vote", "Two proportions (z)"],
      ["Compare average test scores of two different classes", "Two means (t)"],
      ["Compare each runner's time before and after training", "Paired (matched)"],
      ["Compare the proportion of defective parts from two suppliers", "Two proportions (z)"],
    ], "Proportions → z; independent quantitative groups → two-sample t; same subjects measured twice → paired t."),
  ]);

const l4 = lesson("u10.4", "10.4", "Matched or paired samples",
  "When each observation in one sample is naturally paired with one in the other (before/after, twins, same subject), analyze the differences. This removes subject-to-subject variability and becomes a one-sample t-test on the differences.",
  ["Compute d = difference for each pair (be consistent about direction).",
   "H₀: μ_d = 0. t = d̄/(s_d/√n) with df = n − 1.",
   "Requires the differences to be roughly normal or n large.",
   "Paired designs are more powerful when pairs are strongly related."],
  [
    G.pairedDifferences, G.pairedDifferences, G.pairedDifferences,
    mc(p, "Which of these is a matched-pairs design?",
      ["Measuring the same students' anxiety before and after a mindfulness course", "Comparing anxiety of students at two different schools", "Comparing men and women's anxiety scores", "Measuring anxiety in one class only"],
      "The same subjects measured twice form natural pairs."),
    num(p, "Five subjects' weights before and after a program have differences (after − before): −3, −5, 0, −4, −3. Find d̄. (1 decimal.)", -3,
      "Sum = −15; d̄ = −15/5 = −3.0.", { tolerance: 0.01 }),
    num(p, "For the differences −3, −5, 0, −4, −3 (d̄ = −3), find s_d. (2 decimals.)", 1.87,
      "Deviations: 0, −2, 3, −1, 0 → squares 0, 4, 9, 1, 0 (sum 14). s_d = √(14/4) = 1.87.", { tolerance: 0.02 }),
    num(p, "For those differences (d̄ = −3, s_d = 1.87, n = 5), find t. (2 decimals.)", -3.59,
      "t = −3/(1.87/√5) = −3/0.836 = −3.59, df = 4.", { tolerance: 0.05 }),
    mc(p, "In a paired t-test, the degrees of freedom are…",
      ["n − 1, where n is the number of pairs", "n₁ + n₂ − 2", "2n − 1", "n₁ − 1 plus n₂ − 1"],
      "The test is a one-sample t-test on n differences."),
    tf(p, "Analyzing paired data with an independent two-sample t-test is usually wrong because it ignores the pairing and wastes information.", true,
      "Pairing controls for differences between subjects; ignoring it inflates variability and reduces power."),
    mc(p, "Hₐ: μ_d < 0 with d = after − before. The alternative claims that…",
      ["values decreased after the treatment", "values increased after the treatment", "values did not change", "the pairs are independent"],
      "A negative mean difference (after − before) means measurements went down."),
    match(p, "Match the two-sample scenario to the correct test.", [
      ["Independent groups, σ unknown", "2-SampTTest"],
      ["Independent groups, σ known", "2-SampZTest"],
      ["Two proportions", "2-PropZTest"],
      ["Paired data", "T-Test on differences"],
    ], "Naming the design correctly is the key first step."),
    tf(p, "In a matched-pairs test with fewer than 30 pairs, the differences should be approximately normally distributed.", true,
      "The paired t-test is a one-sample t-test on the differences, so the usual normality condition applies to the differences when n is small."),
    mc(p, "Which statement distinguishes matched pairs from independent samples?",
      ["In matched pairs the two measurements come from the same set of individuals, so the samples are dependent", "Matched pairs must have unequal sample sizes", "Independent samples are always larger", "Matched pairs use the z distribution"],
      "Dependence between the two measurements is exactly what the paired analysis exploits by working with differences."),
  ]);

export const unit10 = unit(10, "Hypothesis Testing with Two Samples", "Compare two means, two proportions, or paired measurements.", "🔀", "#8ee000", [l1, l2, l3, l4]);
