import { mc, tf, num, match, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u11";

const l1 = lesson("u11.1", "11.1", "Facts about the chi-square distribution",
  "The chi-square (χ²) distribution is the basis for tests involving counts and variances. Its shape depends on degrees of freedom and it is always non-negative and skewed right.",
  ["χ² values are ≥ 0; the curve is skewed right and becomes more symmetric as df grows.",
   "Mean = df; standard deviation = √(2·df).",
   "Test statistic Σ(O − E)²/E for count data; (n − 1)s²/σ² for a variance.",
   "Chi-square tests are almost always right-tailed."],
  [
    G.chiSquareFacts, G.chiSquareFacts, G.singleVarianceTest,
    mc(p, "Which is true of the chi-square distribution?",
      ["It is skewed right and takes only non-negative values", "It is symmetric about 0", "It is bell-shaped with mean 0", "It takes negative values half the time"],
      "χ² is a sum of squares, so it cannot be negative; its right skew decreases as df increases."),
    num(p, "What is the mean of a chi-square distribution with 12 degrees of freedom?", 12,
      "For χ², mean = df.", { tolerance: 0 }),
    num(p, "What is the standard deviation of a chi-square distribution with 8 degrees of freedom?", 4,
      "σ = √(2·df) = √16 = 4.", { tolerance: 0.01 }),
    mc(p, "As the degrees of freedom increase, the chi-square distribution…",
      ["becomes more symmetric and approaches a normal shape", "becomes more skewed", "shifts to the left", "becomes uniform"],
      "Large df make χ² look increasingly bell-shaped, centered near df."),
    tf(p, "Most chi-square hypothesis tests are right-tailed.", true,
      "Large discrepancies between observed and expected counts produce large χ² values, which fall in the right tail."),
    mc(p, "A chi-square test statistic of 0 would indicate…",
      ["the observed counts exactly matched the expected counts", "strong evidence against H₀", "a calculation error", "a two-tailed test"],
      "Σ(O − E)²/E = 0 only if every O equals its E."),
    mc(p, "The chi-square test statistic for a test of a single variance is…",
      ["(n − 1)s²/σ²", "Σ(O − E)²/E", "(x̄ − μ)/(s/√n)", "s₁²/s₂²"],
      "This statistic compares the sample variance with the hypothesized population variance."),
    mc(p, "A chi-square random variable with df degrees of freedom can be written as…",
      ["Z₁² + Z₂² + … + Z_df², a sum of squares of df independent standard normal variables", "Z₁ + Z₂ + … + Z_df", "the ratio of two normal variables", "the square root of a normal variable"],
      "This is why χ² is never negative and why its mean is df: each Z² has mean 1."),
    mc(p, "For which degrees of freedom does the chi-square curve closely approximate a normal curve, according to the book?",
      ["df greater than 90", "df greater than 2", "df greater than 30", "It never does"],
      "The right skew fades as df grows; beyond about 90 degrees of freedom the curve is nearly bell-shaped."),
  ]);

const l2 = lesson("u11.2", "11.2", "Goodness-of-fit test",
  "A goodness-of-fit test checks whether observed category counts match a hypothesized distribution, such as 'all outcomes equally likely' or 'the population follows these percentages'.",
  ["H₀: the data fit the specified distribution. Hₐ: they do not.",
   "χ² = Σ(O − E)²/E, with df = (number of categories) − 1.",
   "Each expected count should be at least 5.",
   "Right-tailed p-value = P(χ² > statistic)."],
  [
    G.chiSquareGOF, G.chiSquareGOF, G.chiSquareGOF,
    num(p, "A die is rolled 120 times. Under H₀ (fair die), what is the expected count for each face?", 20,
      "E = n × p = 120 × (1/6) = 20.", { tolerance: 0 }),
    num(p, "Observed counts for the die: 15, 22, 18, 25, 20, 20 (expected 20 each). Compute χ². (2 decimals.)", 2.9,
      "(15−20)² = 25, (22−20)² = 4, (18−20)² = 4, (25−20)² = 25, (20−20)² = 0, (20−20)² = 0. Sum = 58; χ² = 58/20 = 2.90.", { tolerance: 0.05 }),
    num(p, "A goodness-of-fit test with 6 categories has how many degrees of freedom?", 5,
      "df = k − 1 = 5.", { tolerance: 0 }),
    mc(p, "A company claims its candy colors are 30% red, 30% green, 40% blue. In a bag of 200, you count 50 red, 60 green, 90 blue. The expected count of red is…",
      ["60", "50", "66.7", "30"],
      "E = 0.30 × 200 = 60."),
    mc(p, "For the candy test, the hypotheses are…",
      ["H₀: the colors follow the 30/30/40 distribution; Hₐ: they do not", "H₀: the colors are equally likely; Hₐ: they are not", "H₀: p_red = 0.25; Hₐ: p_red ≠ 0.25", "H₀: the colors are independent; Hₐ: they are dependent"],
      "Goodness-of-fit compares the data against a fully specified distribution."),
    tf(p, "A large χ² statistic (and small p-value) provides evidence that the data do NOT fit the hypothesized distribution.", true,
      "Big discrepancies inflate the statistic; reject H₀ when p < α."),
    mc(p, "Which condition should be checked before a goodness-of-fit test?",
      ["Every expected count is at least 5", "Every observed count is at least 5", "The sample size is at least 100", "The categories are numerical"],
      "Small expected counts make the χ² approximation unreliable; combine categories if needed."),
  ]);

const l3 = lesson("u11.3", "11.3", "Test of independence",
  "Are two categorical variables related? The test of independence compares the observed counts in a contingency table with the counts expected if the variables were independent.",
  ["H₀: the two variables are independent. Hₐ: they are dependent.",
   "E = (row total)(column total)/(grand total).",
   "df = (rows − 1)(columns − 1).",
   "χ² = Σ(O − E)²/E; right-tailed p-value."],
  [
    G.chiSquareIndependence, G.chiSquareIndependence, G.chiSquareIndependence,
    num(p, "A 3 × 4 contingency table is tested for independence. Find df.", 6,
      "(3 − 1)(4 − 1) = 6.", { tolerance: 0 }),
    num(p, "In a table with row total 80, column total 50, and grand total 200, the expected count for that cell is:", 20,
      "E = 80 × 50/200 = 20.", { tolerance: 0.01 }),
    mc(p, "A survey cross-classifies 300 people by age group and preferred news source. The appropriate test is…",
      ["Chi-square test of independence", "Goodness-of-fit", "Two-sample t-test", "Test of a single variance"],
      "Two categorical variables measured on one sample → test of independence."),
    mc(p, "The null hypothesis of a test of independence states that…",
      ["the two categorical variables are not related", "the two variables have equal means", "all cell counts are equal", "the row totals equal the column totals"],
      "Independence means the distribution of one variable is the same across levels of the other."),
    mc(p, "A test of independence gives p-value 0.002. At α = 0.05, the conclusion is…",
      ["There is sufficient evidence that the variables are dependent (related)", "The variables are independent", "One variable causes the other", "The sample is biased"],
      "Small p → reject independence. Note that dependence does not prove causation."),
    tf(p, "Expected counts in a test of independence are computed under the assumption that the variables are independent.", true,
      "E = (row total)(column total)/n is exactly what independence would predict."),
    mc(p, "A contingency table is…",
      ["a table displaying sample values for two factors that may be dependent on one another", "a list of expected counts only", "a table of z-scores", "a histogram of two variables"],
      "Contingency tables organize joint counts and are the starting point for both conditional probabilities and the test of independence."),
  ]);

const l4 = lesson("u11.4", "11.4", "Test for homogeneity",
  "The test for homogeneity asks whether two or more populations share the same distribution of a categorical variable. It uses the same computations as the test of independence but a different sampling design.",
  ["H₀: the populations have the same distribution. Hₐ: they differ.",
   "Separate samples from each population, one categorical response.",
   "E = (row total)(column total)/n; df = (rows − 1)(columns − 1).",
   "Right-tailed χ² test, same as independence."],
  [
    G.chiSquareIndependence, G.chiSquareIndependence,
    mc(p, "Which question is answered by a test for homogeneity?",
      ["Do students at three different universities have the same distribution of majors?", "Are major and gender related within one university?", "Does the mean GPA differ between two universities?", "Is the proportion of biology majors 20%?"],
      "Homogeneity compares the distribution of one categorical variable across separate populations."),
    mc(p, "What is the key difference between the tests of independence and homogeneity?",
      ["Independence uses one sample classified two ways; homogeneity uses separate samples from several populations", "They use different test statistics", "Homogeneity has more degrees of freedom", "Independence is left-tailed"],
      "The calculations are identical; the sampling design and the wording of the hypotheses differ."),
    num(p, "Three populations are compared on a response with 4 categories. Find df for the homogeneity test.", 6,
      "(3 − 1)(4 − 1) = 6.", { tolerance: 0 }),
    tf(p, "The test for homogeneity can compare more than two populations at once.", true,
      "Any number of populations (rows) can be compared; df grows accordingly."),
    mc(p, "A homogeneity test comparing voting preference across 4 regions gives p = 0.30. Conclusion at α = 0.05?",
      ["There is not sufficient evidence that the regions differ in voting preference", "The regions have identical preferences", "The regions differ significantly", "The test needs more categories"],
      "p > α: fail to reject the null that the distributions are the same."),
    mc(p, "The null hypothesis of a homogeneity test says…",
      ["all populations share the same distribution of the categorical variable", "the populations have equal sizes", "the variables are independent within each population", "the means are equal"],
      "Homogeneous means 'the same' across groups."),
  ]);

const l5 = lesson("u11.5", "11.5", "Comparing the chi-square tests",
  "Three chi-square tests, one formula. Choosing the right one depends on the question and how the data were collected.",
  ["Goodness-of-fit: one variable, does it match a specified distribution? df = k − 1.",
   "Independence: one sample, two variables, are they related? df = (r − 1)(c − 1).",
   "Homogeneity: several populations, one variable, same distribution? df = (r − 1)(c − 1).",
   "All are right-tailed with χ² = Σ(O − E)²/E."],
  [
    G.chiSquareGOF, G.chiSquareIndependence, G.chiSquareFacts,
    classify(p, "Identify the correct chi-square test for each situation.", ["Goodness-of-fit", "Independence", "Homogeneity"], [
      ["Does a die produce each face equally often?", "Goodness-of-fit"],
      ["Among one sample of shoppers, is payment method related to age group?", "Independence"],
      ["Do customers in three cities have the same distribution of payment methods?", "Homogeneity"],
      ["Does the distribution of blood types in a town match national percentages?", "Goodness-of-fit"],
      ["Are smoking status and exercise habit related among surveyed adults?", "Independence"],
    ], "One variable vs. a known distribution → GOF. Two variables in one sample → independence. One variable across separate samples → homogeneity."),
    match(p, "Match each test to its degrees of freedom.", [
      ["Goodness-of-fit with k categories", "k − 1"],
      ["Independence, r × c table", "(r − 1)(c − 1)"],
      ["Single variance, sample size n", "n − 1"],
      ["Homogeneity, 3 populations × 4 categories", "6"],
    ], "Degrees of freedom determine which χ² curve to use."),
    mc(p, "All three chi-square tests share which feature?",
      ["They compare observed counts with expected counts using Σ(O − E)²/E", "They test means", "They are two-tailed", "They require normal data"],
      "The statistic and right-tailed decision are the same; only the setup differs."),
    tf(p, "The test of independence and the test for homogeneity use identical calculations.", true,
      "Only the sampling scheme and the phrasing of the conclusion differ."),
    mc(p, "A researcher has one categorical variable with 5 levels and wants to know whether the levels are equally likely. The test is…",
      ["Goodness-of-fit with df = 4", "Independence with df = 4", "Homogeneity with df = 5", "Test of a single variance"],
      "Comparing one variable against a specified (uniform) distribution is goodness-of-fit; df = 5 − 1 = 4."),
  ]);

const l6 = lesson("u11.6", "11.6", "Test of a single variance",
  "Sometimes the question is about variability rather than the average: is a machine's output consistent enough? The chi-square test of a single variance answers it.",
  ["H₀: σ² = σ₀²; Hₐ: σ² <, >, or ≠ σ₀².",
   "χ² = (n − 1)s²/σ₀², df = n − 1.",
   "Can be left-, right-, or two-tailed depending on Hₐ.",
   "Requires an approximately normal population."],
  [
    G.singleVarianceTest, G.singleVarianceTest,
    mc(p, "A filling machine should have a standard deviation of at most 2 mL. A sample of 25 bottles has s = 2.8 mL. The hypotheses are…",
      ["H₀: σ² = 4, Hₐ: σ² > 4", "H₀: σ² = 4, Hₐ: σ² < 4", "H₀: μ = 2, Hₐ: μ > 2", "H₀: s = 2, Hₐ: s > 2"],
      "The concern is excessive variability, so the alternative is right-tailed on the variance σ² = 2² = 4."),
    num(p, "For that machine (n = 25, s = 2.8, σ₀ = 2), compute χ². (2 decimals.)", 47.04,
      "(24)(2.8²)/2² = 24 × 7.84/4 = 47.04, df = 24.", { tolerance: 0.05 }),
    mc(p, "χ² = 47.04 with df = 24 gives a right-tailed p-value ≈ 0.003. At α = 0.05…",
      ["Reject H₀: the variability exceeds the standard", "Do not reject H₀", "Accept H₀: the machine is fine", "Use a t-test instead"],
      "p < α provides evidence that the true standard deviation is larger than 2 mL."),
    tf(p, "The test of a single variance is always right-tailed.", false,
      "Unlike the count-based tests, it can be left-tailed (testing for reduced variability), right-tailed, or two-tailed."),
    num(p, "What are the degrees of freedom for a single-variance test with n = 31?", 30,
      "df = n − 1 = 30.", { tolerance: 0 }),
    mc(p, "If the sample variance equals the hypothesized variance exactly, the χ² statistic equals…",
      ["n − 1", "0", "1", "n"],
      "(n − 1)s²/σ₀² with s² = σ₀² gives n − 1, the mean of the χ² distribution."),
  ]);

export const unit11 = unit(11, "The Chi-Square Distribution", "Tests for counts and variances: goodness-of-fit, independence, homogeneity, and a single variance.", "🧩", "#a560e8", [l1, l2, l3, l4, l5, l6]);
