import { mc, tf, num, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u12";

const l1 = lesson("u12.1", "12.1", "Linear equations",
  "Regression begins with straight lines. A linear equation y = a + bx has a slope b (change in y per unit of x) and a y-intercept a (the value of y when x is 0). Interpreting both in context is the core skill.",
  ["y = a + bx: a is the y-intercept, b is the slope.",
   "Slope > 0: line rises; slope < 0: line falls; slope = 0: horizontal.",
   "Slope units = (units of y)/(units of x).",
   "Independent variable x (input), dependent variable y (output)."],
  [
    G.linearEquation, G.linearEquation, G.linearEquation,
    mc(p, "In the equation y = 15 + 0.5x describing a phone plan (x = minutes, y = cost in dollars), what does 15 represent?",
      ["A fixed monthly charge of $15 even with zero minutes", "A charge of $15 per minute", "The maximum bill", "The number of free minutes"],
      "The y-intercept is the value of y when x = 0: the base cost with no minutes used."),
    mc(p, "In y = 15 + 0.5x (x = minutes, y = dollars), the slope 0.5 means…",
      ["each additional minute costs $0.50", "the plan includes 0.5 minutes", "the bill is half the minutes", "cost decreases by $0.50 per minute"],
      "Slope is the change in y per one-unit increase in x."),
    num(p, "Using y = 15 + 0.5x, what is the cost for 200 minutes?", 115,
      "y = 15 + 0.5(200) = 15 + 100 = 115.", { tolerance: 0.01 }),
    mc(p, "A line has a negative slope. As x increases, y…",
      ["decreases", "increases", "stays the same", "becomes negative"],
      "Negative slope means the line falls from left to right."),
    tf(p, "In a linear model, the independent variable is plotted on the horizontal (x) axis.", true,
      "x is the explanatory/independent variable; y is the response/dependent variable on the vertical axis."),
    mc(p, "Which equation represents a line with y-intercept 4 and slope −2?",
      ["y = 4 − 2x", "y = −2 + 4x", "y = 2x − 4", "y = 4x − 2"],
      "y = a + bx with a = 4 and b = −2."),
    num(p, "A line passes through (2, 10) and (6, 22). What is its slope?", 3,
      "Slope = (22 − 10)/(6 − 2) = 12/4 = 3.", { tolerance: 0.01 }),
    mc(p, "Is the equation y = 10 + 5x − 3x² linear?",
      ["No, because of the x² term the graph is a curve, not a straight line", "Yes, because it has a y-intercept", "Yes, because it contains x", "No, because the coefficient 5 is positive"],
      "A linear equation has the form y = a + bx with x to the first power only."),
    classify(p, "Which equations are linear?", ["Linear", "Not linear"], [
      ["y = 6x + 8", "Linear"],
      ["y + 7 = 3x", "Linear"],
      ["y − x = 8x²", "Not linear"],
      ["4y = 8", "Linear"],
    ], "Rearranged, y + 7 = 3x is y = −7 + 3x and 4y = 8 is y = 2 (slope 0); both are straight lines. Any squared term makes a curve."),
  ]);

const l2 = lesson("u12.2", "12.2", "Scatter plots",
  "A scatter plot shows paired (x, y) data as points. Before fitting a line, look for the direction, form, and strength of any relationship, and for outliers.",
  ["Direction: positive (rising) or negative (falling).",
   "Form: linear or curved. Strength: how tightly the points cluster around a pattern.",
   "Outliers: points far from the overall pattern.",
   "A scatter plot showing no pattern suggests no linear relationship."],
  [
    G.correlationStrength, G.correlationStrength,
    mc(p, "A scatter plot of hours studied (x) vs. exam score (y) shows points rising from lower-left to upper-right, tightly clustered. The relationship is…",
      ["strong positive linear", "weak positive linear", "strong negative linear", "no relationship"],
      "Rising = positive; tightly clustered = strong; a straight-line pattern = linear."),
    mc(p, "A scatter plot of car age (x) vs. resale value (y) shows points falling from upper-left to lower-right. The relationship is…",
      ["negative", "positive", "nonexistent", "curved upward"],
      "As age increases, value decreases: a negative association."),
    mc(p, "Which scatter plot pattern suggests a linear model would be inappropriate?",
      ["Points following a clear U-shaped curve", "Points scattered tightly around a rising line", "Points scattered loosely around a falling line", "Points on a perfectly straight line"],
      "A curved pattern needs a nonlinear model; lines only capture straight-line trends."),
    mc(p, "In a scatter plot, one point lies far above all the others. This point is…",
      ["a potential outlier that may influence the regression line", "the y-intercept", "the mean of the data", "always an error"],
      "Points far from the pattern can pull the fitted line; investigate them but do not automatically delete them."),
    tf(p, "In a scatter plot, the explanatory variable goes on the vertical axis.", false,
      "The explanatory (independent) variable goes on the horizontal x-axis; the response on the vertical y-axis."),
    mc(p, "Points in a scatter plot show no visible pattern at all. The most appropriate conclusion is…",
      ["there is little or no linear relationship between the variables", "the relationship is strongly positive", "the data are invalid", "y depends strongly on x"],
      "A random cloud of points means x tells us little about y, at least linearly."),
    order(p, "Order the steps for exploring a bivariate relationship.", [
      "Identify the explanatory (x) and response (y) variables",
      "Draw a scatter plot",
      "Describe direction, form, and strength, and note outliers",
      "If the pattern is linear, fit a regression line",
    ], "Always look before you compute."),
  ]);

const l3 = lesson("u12.3", "12.3", "The regression equation",
  "The least-squares regression line ŷ = a + bx is the line that minimizes the sum of squared vertical distances (residuals) from the points. The correlation coefficient r measures how well a line describes the data.",
  ["ŷ = a + bx is the predicted y; residual = y − ŷ.",
   "Least squares minimizes Σ(y − ŷ)²; the line passes through (x̄, ȳ).",
   "r ranges from −1 to 1; sign matches the slope; |r| near 1 means strong linear fit.",
   "r² = coefficient of determination: fraction of the variation in y explained by the line."],
  [
    G.regressionFromData, G.regressionFromData, G.correlationStrength, G.correlationStrength,
    mc(p, "The least-squares line is the line that…",
      ["minimizes the sum of the squared residuals", "passes through the most points", "minimizes the sum of the residuals", "has the smallest slope"],
      "Squaring keeps residuals positive and penalizes large misses, giving a unique best line."),
    num(p, "A regression gives ŷ = 3 + 2x. A data point has x = 4 and y = 13. What is its residual?", 2,
      "ŷ = 3 + 2(4) = 11. Residual = y − ŷ = 13 − 11 = 2.", { tolerance: 0.01 }),
    mc(p, "A correlation coefficient r = 0.9 means…",
      ["a strong positive linear relationship", "90% of the points lie on the line", "y increases by 0.9 for each unit of x", "the relationship is weak"],
      "r near +1 means points cluster tightly around a rising line. It is not a slope or a percentage of points."),
    mc(p, "If r = −0.8, then r² = 0.64. The interpretation of r² is…",
      ["64% of the variation in y is explained by the linear relationship with x", "64% of the points are on the line", "the slope is 0.64", "y decreases by 64%"],
      "r² is the coefficient of determination: the share of variation in y accounted for by the regression line."),
    tf(p, "The sign of the correlation coefficient always matches the sign of the regression slope.", true,
      "Both are computed from the same covariance, so they share a sign."),
    mc(p, "Which value of r indicates the weakest linear relationship?",
      ["r = 0.05", "r = −0.85", "r = 0.6", "r = −0.4"],
      "Strength depends on |r|; 0.05 is closest to 0."),
    mc(p, "The regression line for predicting weight (lb) from height (in) is ŷ = −200 + 5x. What does the slope mean?",
      ["Each additional inch of height is associated with 5 more pounds, on average", "A person 0 inches tall weighs −200 lb", "Height causes weight to increase by 5 lb", "5% of weight is explained by height"],
      "Slope is the average change in y per unit of x; a regression describes association, not causation."),
    match(p, "Match each regression term to its meaning.", [
      ["Residual", "y − ŷ, the vertical miss of the line"],
      ["r", "Strength and direction of the linear relationship"],
      ["r²", "Fraction of variation in y explained by x"],
      ["ŷ", "The predicted value of y"],
    ], "These four terms are the vocabulary of regression output."),
  ]);

const l4 = lesson("u12.4", "12.4", "Testing the significance of the correlation coefficient",
  "The sample r estimates the population correlation ρ. Before using the line to predict, test H₀: ρ = 0 to see whether the linear relationship is real or could be due to chance.",
  ["H₀: ρ = 0 (no linear relationship). Hₐ: ρ ≠ 0.",
   "t = r√((n − 2)/(1 − r²)) with df = n − 2; or compare |r| with the critical value from a table.",
   "If p < α (or |r| > critical value), r is significant and the line may be used for prediction.",
   "Significance depends on both r and n: a small r can be significant with large n.",
   "Conditions for regression: Linear relationship, Independent residuals, Normal y-values at each x, Equal variance at each x, Random data. The sample slope b and intercept a estimate the population β and α; s (SD of the residuals) estimates σ."],
  [
    G.rCritical, G.rCritical,
    mc(p, "The null hypothesis when testing the correlation coefficient is…",
      ["H₀: ρ = 0", "H₀: r = 0", "H₀: ρ = 1", "H₀: b = 1"],
      "The test concerns the population correlation ρ; r is the sample value we compute."),
    num(p, "What are the degrees of freedom for testing the correlation with n = 20 pairs?", 18,
      "df = n − 2 = 18.", { tolerance: 0 }),
    num(p, "With n = 20 and r = 0.6, compute the test statistic t = r√((n − 2)/(1 − r²)). (2 decimals.)", 3.18,
      "0.6 × √(18/0.64) = 0.6 × 5.303 = 3.18.", { tolerance: 0.03 }),
    mc(p, "The test of ρ gives p-value 0.001 at α = 0.05. What is the conclusion?",
      ["There is significant evidence of a linear relationship; the regression line may be used for prediction", "There is no linear relationship", "x causes y", "The slope equals zero"],
      "Rejecting H₀: ρ = 0 means the linear relationship is unlikely to be due to chance."),
    mc(p, "If r is NOT significant, then…",
      ["the regression line should not be used to predict y from x", "the slope must be zero in the sample", "the correlation is negative", "more data will always make it significant"],
      "Without evidence of a real linear relationship, predictions from the line are not justified."),
    tf(p, "With a very large sample, even a small correlation such as r = 0.15 can be statistically significant.", true,
      "The t statistic grows with √(n − 2), so large n can make modest correlations significant; judge practical importance separately."),
    mc(p, "A significant correlation between ice cream sales and drownings most likely reflects…",
      ["a lurking variable (hot weather) rather than causation", "that ice cream causes drowning", "a calculation error", "that r must be negative"],
      "Correlation shows association; a third variable often explains it."),
    classify(p, "Match each condition for linear regression to its description.", ["Linear", "Independent", "Normal", "Equal variance", "Random"], [
      ["The average y changes along a straight line as x changes", "Linear"],
      ["The residuals do not influence one another", "Independent"],
      ["For each x, the y values follow a bell-shaped distribution", "Normal"],
      ["The spread of y is the same at every x", "Equal variance"],
      ["The data come from a well-designed random sample or experiment", "Random"],
    ], "These five conditions justify using the t-test for the correlation coefficient and the regression line for prediction."),
    match(p, "Match each sample quantity to the population quantity it estimates.", [
      ["b (sample slope)", "β (population slope)"],
      ["a (sample intercept)", "α (population intercept)"],
      ["r (sample correlation)", "ρ (population correlation)"],
      ["s (SD of residuals)", "σ (SD of y about the line)"],
    ], "Roman letters are sample statistics; Greek letters are the population parameters they estimate."),
  ]);

const l5 = lesson("u12.5", "12.5", "Prediction",
  "Once the correlation is significant, plug an x value into ŷ = a + bx to predict y. But only predict within the range of the observed x values; extrapolating beyond it is unreliable.",
  ["Prediction: substitute x into the regression equation.",
   "Interpolation (within the x range) is reasonable; extrapolation (outside it) is risky.",
   "The line predicts the average y for a given x, not an exact individual value."],
  [
    G.regressionFromData, G.linearEquation,
    num(p, "ŷ = 12 + 3.5x predicts weekly sales (hundreds of dollars) from ad spending x (hundreds). Data cover x from 2 to 10. Predict sales when x = 6.", 33,
      "ŷ = 12 + 3.5(6) = 33 (hundred dollars).", { tolerance: 0.01 }),
    mc(p, "Using the same model (data x from 2 to 10), a manager wants to predict sales for x = 40. This is…",
      ["extrapolation and should not be trusted", "interpolation and is reliable", "acceptable because the correlation is significant", "impossible to compute"],
      "x = 40 is far outside the observed range; the linear pattern may not hold there."),
    mc(p, "The predicted value ŷ for a given x is best interpreted as…",
      ["the average y for all individuals with that x", "the exact y for the next individual with that x", "the maximum y possible", "the residual"],
      "The line estimates the mean response; individual values scatter around it."),
    tf(p, "If the correlation is not significant, the best prediction for y at any x is simply ȳ, the mean of y.", true,
      "Without a usable linear relationship, x adds no information, so the sample mean of y is the best guess."),
    mc(p, "A regression of exam score on hours studied uses data from students who studied 0 to 15 hours. Which prediction is interpolation?",
      ["Predicting the score for 8 hours", "Predicting the score for 30 hours", "Predicting the score for 50 hours", "Predicting hours from a score of 200"],
      "8 hours lies inside the observed range."),
    order(p, "Order the steps for making a valid prediction with regression.", [
      "Draw a scatter plot and check for a linear pattern",
      "Compute the least-squares line and r",
      "Test whether r is significant",
      "Confirm the x value is within the data range",
      "Substitute x into ŷ = a + bx",
    ], "Each step guards against a common misuse of regression."),
  ]);

const l6 = lesson("u12.6", "12.6", "Outliers in regression",
  "Outliers are points that fall far from the regression line. They can distort the slope and correlation, so identify them, investigate them, and report how they affect the fit.",
  ["Rule of thumb: a point is an outlier if |residual| ≥ 2s, where s = √(SSE/(n − 2)) is the standard deviation of the residuals.",
   "Alternatively, draw lines 2s above and below the regression line; points outside are outliers.",
   "Influential points change the slope substantially when removed.",
   "Remove an outlier only with a good reason (data error, different population); always report it."],
  [
    G.residualOutlier, G.residualOutlier,
    mc(p, "In regression, an outlier is a point that…",
      ["has a residual much larger in magnitude than the others", "has the largest x value", "lies exactly on the line", "has y equal to ȳ"],
      "Outliers are judged by their vertical distance from the line, i.e., the residual."),
    num(p, "A regression has SSE = 72 with n = 10 points. Compute s = √(SSE/(n − 2)). (Round to 1 decimal.)", 3,
      "s = √(72/8) = √9 = 3.", { tolerance: 0.05 }),
    mc(p, "Using s = 3, a point with residual −7 is…",
      ["an outlier, because |−7| > 2s = 6", "not an outlier, because it is negative", "not an outlier, because 7 < 3s", "impossible"],
      "The 2s rule flags any point whose residual exceeds 6 in absolute value."),
    mc(p, "After removing an outlier, the slope changes from 1.2 to 2.5 and r rises from 0.4 to 0.8. The removed point was…",
      ["influential", "irrelevant", "the y-intercept", "the mean of the data"],
      "A point whose removal substantially changes the line is called influential."),
    tf(p, "Outliers should always be deleted from the data before running a regression.", false,
      "Delete only with justification (a recording error, a case from a different population) and always report what was done. Some outliers are the most interesting data."),
    mc(p, "Which is a legitimate reason to remove an outlier from a regression analysis?",
      ["It was found to be a data-entry error", "It makes r smaller", "It is inconvenient", "It has the largest residual"],
      "Removing points merely to improve the fit is dishonest; verified errors are a valid reason."),
    mc(p, "The standard deviation of the residuals, s, is computed with n − 2 in the denominator because…",
      ["two parameters (a and b) were estimated from the data", "there are two variables", "n − 2 makes s smaller", "the residuals sum to 2"],
      "Each estimated parameter uses up a degree of freedom, and the regression line has two."),
    mc(p, "Graphically, the outlier rule draws two lines parallel to the regression line. Where are they?",
      ["At ŷ + 2s and ŷ − 2s; points outside them are outliers", "At ŷ + s and ŷ − s", "At the maximum and minimum y", "At Q₁ and Q₃ of y"],
      "Any point above the upper line or below the lower line has a residual of at least 2s in absolute value."),
  ]);

export const unit12 = unit(12, "Linear Regression and Correlation", "Fit lines to data, measure correlation, test significance, and predict responsibly.", "📉", "#3caea3", [l1, l2, l3, l4, l5, l6]);
