import { mc, tf, num, match, order, classify, lesson, unit } from "./helpers";
import * as G from "../engine/generators";

const p = "u13";

const l1 = lesson("u13.1", "13.1", "One-way ANOVA",
  "Analysis of variance (ANOVA) compares the means of three or more groups at once. Instead of running many t-tests, it asks whether the variation between group means is large relative to the variation within groups.",
  ["H₀: μ₁ = μ₂ = … = μ_k. Hₐ: at least one mean differs (not 'all differ').",
   "Five assumptions: each population is normal; equal population standard deviations; samples are random and independent; groups may differ in size; one factor (independent variable) and one response (dependent variable).",
   "Compares between-group variance with within-group variance.",
   "Rejecting H₀ says some means differ, not which ones."],
  [
    G.anovaDF, G.anovaDF,
    mc(p, "A researcher compares the mean yields of four fertilizer types. The appropriate test is…",
      ["One-way ANOVA", "Two-sample t-test", "Chi-square test of independence", "Paired t-test"],
      "Comparing means across more than two groups is exactly what one-way ANOVA does."),
    mc(p, "The alternative hypothesis in one-way ANOVA is…",
      ["At least one population mean is different from the others", "All population means are different", "All population means are equal", "The variances are unequal"],
      "ANOVA detects any departure from 'all equal'; it does not require every mean to differ."),
    mc(p, "Why not just run t-tests on every pair of groups instead of ANOVA?",
      ["Many tests inflate the overall chance of a Type I error", "t-tests cannot compare means", "ANOVA is required by law", "t-tests need equal sample sizes"],
      "With 4 groups there are 6 pairwise tests; at α = 0.05 each, the chance of at least one false rejection is far above 5%."),
    tf(p, "One-way ANOVA assumes the populations have approximately equal variances.", true,
      "Equal variances (and normality, and independent random samples) are the standard ANOVA assumptions."),
    mc(p, "ANOVA rejects H₀ for three groups. What has been shown?",
      ["At least one group mean differs from another", "All three means are different", "Group 1 has the largest mean", "The variances differ"],
      "Follow-up comparisons are needed to see which specific means differ."),
    mc(p, "The 'one-way' in one-way ANOVA refers to…",
      ["a single factor (grouping variable) being studied", "a one-tailed test", "one observation per group", "one degree of freedom"],
      "One factor with several levels; two-way ANOVA would have two factors."),
    classify(p, "Which of these are assumptions of one-way ANOVA?", ["Assumption", "Not an assumption"], [
      ["Each population is approximately normal", "Assumption"],
      ["The populations have equal standard deviations", "Assumption"],
      ["Samples are random and independent", "Assumption"],
      ["All groups must have the same sample size", "Not an assumption"],
      ["There is one independent (factor) variable and one dependent variable", "Assumption"],
    ], "Group sizes may differ (unbalanced data); the other four statements are the standard conditions."),
    mc(p, "Data with the same number of observations in every group are called…",
      ["balanced", "pooled", "paired", "stratified"],
      "With balanced data the F ratio simplifies to n·(variance of the group means)/(mean of the group variances)."),
  ]);

const l2 = lesson("u13.2", "13.2", "The F distribution and the F ratio",
  "The ANOVA test statistic is an F ratio: the mean square between groups divided by the mean square within groups. If H₀ is true the ratio is near 1; large values are evidence that the means differ.",
  ["SS(between) measures spread of group means; SS(within) measures spread inside groups.",
   "MS(between) = SS(between)/(k − 1); MS(within) = SS(within)/(N − k).",
   "F = MS(between)/MS(within), with df = (k − 1, N − k).",
   "Right-tailed test: p-value = P(F > statistic).",
   "Equal group sizes: F = n·s²_x̄ / (mean of the sample variances), where s²_x̄ is the variance of the group means."],
  [
    G.anovaFRatio, G.anovaFRatio, G.anovaFRatio,
    num(p, "Three groups of 8 observations each: SS(between) = 90, SS(within) = 210. Find MS(between).", 45,
      "df(between) = 3 − 1 = 2; MS = 90/2 = 45.", { tolerance: 0.01 }),
    num(p, "Same data (SS(within) = 210, N = 24, k = 3). Find MS(within).", 10,
      "df(within) = 24 − 3 = 21; MS = 210/21 = 10.", { tolerance: 0.01 }),
    num(p, "Same data. Compute F = MS(between)/MS(within). (1 decimal.)", 4.5,
      "F = 45/10 = 4.5 with df = (2, 21).", { tolerance: 0.05 }),
    mc(p, "F = 4.5 with df = (2, 21) has p-value ≈ 0.024. At α = 0.05…",
      ["Reject H₀: at least one group mean differs", "Do not reject H₀", "Accept H₀: all means are equal", "The test is two-tailed, so double the p-value"],
      "0.024 < 0.05. ANOVA is right-tailed; no doubling."),
    mc(p, "If the null hypothesis of ANOVA is true, the F ratio should be…",
      ["close to 1", "close to 0", "very large", "negative"],
      "Both mean squares estimate the same variance under H₀, so their ratio hovers around 1."),
    tf(p, "In ANOVA, a large F statistic indicates that the variation between group means is large compared with the variation within groups.", true,
      "That is exactly the evidence that the group means are not all equal."),
    match(p, "Match each ANOVA quantity to its formula.", [
      ["df(between)", "k − 1"],
      ["df(within)", "N − k"],
      ["MS(between)", "SS(between)/(k − 1)"],
      ["F", "MS(between)/MS(within)"],
    ], "The ANOVA table is built from these four pieces."),
    G.anovaEqualSizes, G.anovaEqualSizes,
  ]);

const l3 = lesson("u13.3", "13.3", "Facts about the F distribution",
  "The F distribution is a ratio of two chi-square variables scaled by their degrees of freedom. It has two df parameters, is skewed right, and takes only non-negative values.",
  ["F has numerator df and denominator df; write F ~ F(df₁, df₂).",
   "F ≥ 0, skewed right, approaches normal-ish symmetry as both df grow.",
   "Mean μ = df₂/(df₂ − 2) for df₂ > 2 (close to 1 for large df₂). Shape can be mounded or exponential-looking depending on the two df.",
   "ANOVA tests are right-tailed."],
  [
    G.anovaDF, G.anovaFRatio,
    mc(p, "Which is true of the F distribution?",
      ["It is skewed right and takes only non-negative values", "It is symmetric about 0", "It has one degree-of-freedom parameter", "It can take negative values"],
      "F is a ratio of variances, so it is non-negative with a long right tail."),
    mc(p, "In F(3, 20), what do 3 and 20 represent?",
      ["Numerator df = 3 and denominator df = 20", "3 groups and 20 observations", "The mean and variance", "The minimum and maximum"],
      "The first number is df for the numerator (between), the second for the denominator (within)."),
    num(p, "An ANOVA compares 4 groups with a total of 24 observations. What is the numerator df of the F statistic?", 3,
      "df₁ = k − 1 = 3.", { tolerance: 0 }),
    num(p, "Same ANOVA (4 groups, 24 observations). What is the denominator df?", 20,
      "df₂ = N − k = 20.", { tolerance: 0 }),
    tf(p, "The F distribution becomes more symmetric as the degrees of freedom increase.", true,
      "Like the chi-square, its skew diminishes with more df."),
    mc(p, "The p-value for an ANOVA F test is found as…",
      ["the area to the right of the F statistic", "the area to the left of the F statistic", "twice the area to the right", "the area between −F and F"],
      "Only large F values contradict H₀, so the test is right-tailed."),
    mc(p, "An F statistic close to 0 would indicate…",
      ["the group means are nearly identical relative to the within-group spread", "strong evidence that the means differ", "a computational error", "unequal variances"],
      "Tiny between-group variation gives a small F."),
    G.fDistributionMean, G.fDistributionMean,
    mc(p, "If the null hypothesis of equal means is true, the numerator of the F ratio (MS between) should be…",
      ["small compared with the denominator, giving F near 1 and a large p-value", "much larger than the denominator", "exactly zero", "negative"],
      "Under H₀ the group means vary only by chance, so between-group variation is comparable to within-group variation."),
  ]);

const l4 = lesson("u13.4", "13.4", "Test of two variances",
  "The F distribution also compares the variances of two normal populations, which is useful for checking the equal-variance assumption before a pooled t-test or ANOVA.",
  ["H₀: σ₁² = σ₂² (or σ₁²/σ₂² = 1). F = s₁²/s₂² with df = (n₁ − 1, n₂ − 1).",
   "Requires both populations to be nearly normal (this test is sensitive to non-normality).",
   "Can be one- or two-tailed; many put the larger variance in the numerator so F > 1.",
   "Calculator: 2-SampFTest."],
  [
    G.twoVariancesF, G.twoVariancesF,
    mc(p, "A teacher wants to know whether two sections of a course have different variability in exam scores. The test is…",
      ["F test of two variances", "Two-sample t-test", "Chi-square goodness-of-fit", "ANOVA"],
      "Comparing two population variances calls for the F test."),
    num(p, "Section A: s = 9, n = 16. Section B: s = 6, n = 21. Compute F = s₁²/s₂². (2 decimals.)", 2.25,
      "F = 81/36 = 2.25 with df = (15, 20).", { tolerance: 0.01 }),
    mc(p, "For the two-variance test with Section A (n = 16) as numerator and Section B (n = 21) as denominator, the degrees of freedom are…",
      ["(15, 20)", "(16, 21)", "(20, 15)", "(35, 2)"],
      "df = (n₁ − 1, n₂ − 1)."),
    mc(p, "F = 2.25 with df (15, 20) gives a two-tailed p-value ≈ 0.09. At α = 0.05…",
      ["Do not reject H₀: no significant evidence that the variances differ", "Reject H₀: the variances differ", "Accept H₀: the variances are equal", "Use ANOVA instead"],
      "0.09 > 0.05: insufficient evidence of a difference in variability."),
    tf(p, "The F test for two variances is robust to non-normal populations.", false,
      "It is quite sensitive to departures from normality; check the data's shape before relying on it."),
    mc(p, "If the two sample variances are equal, the F statistic equals…",
      ["1", "0", "n₁ − 1", "the sum of the variances"],
      "s₁²/s₂² = 1 when the variances match, which is the null expectation."),
    order(p, "Order the steps of a two-variance F test.", [
      "State H₀: σ₁² = σ₂² and choose Hₐ",
      "Verify both populations are approximately normal",
      "Compute F = s₁²/s₂² and df = (n₁ − 1, n₂ − 1)",
      "Find the p-value and compare with α",
      "State the conclusion in context",
    ], "Checking normality is essential for this particular test."),
  ]);

export const unit13 = unit(13, "F Distribution and One-Way ANOVA", "Compare several means with ANOVA and compare two variances with the F test.", "🏁", "#f5a623", [l1, l2, l3, l4]);
